slice_name: FMR - UHS - Details - PIMCO
viz_type: table
params:
  adhoc_filters: []
  align_pn: true
  all_columns:
  - client_number
  - salutation
  - "\u0E34investor_name_unmasked"
  - investor_typ_txt
  - crr_description
  - investor_age
  - account_number
  - act_description
  - primary_indicator
  - ivc_long_name
  - ccy_id
  - total_units_owned
  - total_value_owned
  - percentage_of_share_class
  color_pn: false
  column_config:
    percentage_of_share_class:
      d3NumberFormat: ',.2%'
      d3SmallNumberFormat: ',.2%'
    total_units_owned:
      d3NumberFormat: ',.4f'
      d3SmallNumberFormat: ',.4f'
    total_value_owned:
      d3NumberFormat: ',.2f'
      d3SmallNumberFormat: ',.2f'
  conditional_formatting: []
  datasource: 54__table
  extra_form_data: {}
  granularity_sqla: latest_valuation_date
  groupby: []
  include_search: true
  metrics: null
  order_by_cols: []
  order_desc: true
  page_length: 10
  percent_metrics: []
  query_mode: raw
  row_limit: '30000'
  server_page_length: 10
  show_cell_bars: false
  slice_id: 389
  table_timestamp_format: smart_date
  time_grain_sqla: P1D
  time_range: No filter
  url_params: {}
  viz_type: table
cache_timeout: null
uuid: 3bc304b6-1e79-433a-be84-e47e38f8965f
version: 1.0.0
dataset_uuid: 294bb475-bd97-fe6c-dec6-ec4cd42fc6fa
