slice_name: SI0 - Funds with Negative Movement
viz_type: filter_box
params:
  adhoc_filters:
  - clause: WHERE
    comparator: '0'
    expressionType: SIMPLE
    filterOptionName: filter_lucg96n3v7o_o75l0tnu3jf
    isExtra: false
    isNew: false
    operator: <
    sqlExpression: null
    subject: Net Movement Percent
  datasource: 29__table
  date_filter: false
  filter_configs:
  - asc: true
    clearable: true
    column: investment_vehicle
    key: XtETA0fZY
    label: Fund Name
    multiple: false
    searchAllOptions: false
  instant_filtering: true
  queryFields: {}
  slice_id: 77
  time_range: Last week
  url_params: {}
  viz_type: filter_box
cache_timeout: null
uuid: 0dbe4687-8e8d-0258-cd44-3e3ba2673a5b
version: 1.0.0
dataset_uuid: b7a6fe58-57ec-ae45-849e-d27bf2cd4961
