slice_name: SI6 - Active Work Work Type Filter
viz_type: filter_box
params:
  adhoc_filters: []
  datasource: 2000000005__table
  date_filter: false
  extra_form_data: {}
  filter_configs:
  - asc: true
    clearable: true
    column: wrktype
    key: MVBT55VGP
    label: WORKTYPE
    multiple: true
    searchAllOptions: false
  granularity_sqla: last_update_dattim
  instant_filtering: true
  slice_id: 2000000037
  time_grain_sqla: P1D
  time_range: No filter
  url_params: {}
  viz_type: filter_box
cache_timeout: null
uuid: d002bff5-da17-41b8-bcab-cdabc855e479
version: 1.0.0
dataset_uuid: deb426d2-5ea7-42ae-ae97-c99694c2ddff
