slice_name: Mockup for SI UK - Money Laundering Status by Client Type
viz_type: dist_bar
params:
  adhoc_filters: []
  bar_stacked: true
  bottom_margin: auto
  color_scheme: supersetColors
  columns:
  - client_type
  contribution: false
  datasource: 93__table
  extra_form_data: {}
  granularity_sqla: eff_date
  groupby:
  - anti_money_laundering_status
  metrics:
  - aggregate: COUNT_DISTINCT
    column:
      certification_details: null
      certified_by: null
      column_name: unitholder_id
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 3126
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: VARCHAR(40)
      type_generic: 1
      verbose_name: Client ID
      warning_markdown: null
    expressionType: SIMPLE
    hasCustomLabel: false
    isNew: false
    label: COUNT_DISTINCT(Client ID)
    optionName: metric_pbxtxmz9m5d_4z6drwlwmaj
    sqlExpression: null
  order_desc: true
  reduce_x_ticks: false
  row_limit: 10000
  show_bar_value: false
  time_range: No filter
  url_params: {}
  viz_type: dist_bar
  x_ticks_layout: auto
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
cache_timeout: null
uuid: 3174500b-2579-4763-a84c-bef603039969
version: 1.0.0
dataset_uuid: 74fa6896-5e25-4630-b057-9f43589743fa
