slice_name: SI0 - Complaints Received/Resolved
viz_type: dist_bar
params:
  adhoc_filters: []
  bottom_margin: auto
  color_scheme: supersetColors
  columns: []
  datasource: 26__table
  extra_form_data: {}
  granularity_sqla: received_date
  groupby:
  - Received Week
  metrics:
  - count
  - Count Resolved
  order_desc: true
  row_limit: 10000
  show_legend: true
  slice_id: 71
  time_range: '2020-10-01 : 2020-10-31'
  url_params: {}
  viz_type: dist_bar
  x_axis_label: Week Commencing
  x_ticks_layout: auto
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  y_axis_label: Number of Complaints
cache_timeout: null
uuid: 2c688490-31b9-d378-ba05-96dd71630c1a
version: 1.0.0
dataset_uuid: af78bd0b-0a57-8bef-89a5-69708c564105
