slice_name: SI6 - Active Work List View
viz_type: table
params:
  adhoc_filters:
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_sf3uyagc4s_xjvb3xdai5n
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: UPPER(queuecd) <> 'END'
    subject: null
  all_columns: []
  color_pn: false
  conditional_formatting: []
  datasource: 2000000005__table
  extra_form_data: {}
  granularity_sqla: last_update_dattim
  groupby:
  - awd_crdattim
  - unitcd
  - wrktype
  - processing_stage
  - suspend_flag
  - age_bus_days_band
  include_search: true
  order_by_cols: []
  order_desc: false
  page_length: 20
  percent_metrics: []
  query_mode: aggregate
  row_limit: 10000
  server_page_length: 10
  show_cell_bars: false
  slice_id: 2000000034
  table_timestamp_format: smart_date
  time_grain_sqla: P1D
  time_range: No filter
  timeseries_limit_metric:
    aggregate: null
    column: null
    expressionType: SQL
    hasCustomLabel: false
    isNew: false
    label: awd_crdattim
    optionName: metric_2o8m8mzoatc_m5ucefay79n
    sqlExpression: awd_crdattim
  url_params: {}
  viz_type: table
cache_timeout: null
uuid: 734e2bd3-6c81-4ed2-8bb6-2630d2cc700d
version: 1.0.0
dataset_uuid: deb426d2-5ea7-42ae-ae97-c99694c2ddff
