slice_name: SI - Largest Negative Fund Movement by Value
viz_type: big_number_total
params:
  adhoc_filters: []
  datasource: 58__table
  header_font_size: 0.4
  metric: Largest Negative Movement Value
  slice_id: 233
  subheader_font_size: 0.15
  time_range: Last week
  url_params: {}
  viz_type: big_number_total
  y_axis_format: .3s
cache_timeout: null
uuid: 9dc1c25e-fad0-f9e3-8e59-da7ec072b45a
version: 1.0.0
dataset_uuid: c28fef52-923b-a734-0b83-4cec471c48cc
