slice_name: SI - Control failures
viz_type: table
params:
  adhoc_filters:
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_74xet4q1h1h_0tzh2srhv49
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: original_closed_date >= date_trunc('Week',(current_date - INTERVAL
      '3 weeks'))::date
    subject: null
  all_columns: []
  color_pn: true
  column_config:
    COUNT:
      d3NumberFormat: ',d'
      d3SmallNumberFormat: ',d'
      horizontalAlign: right
      showCellBars: false
  conditional_formatting: []
  datasource: 48__table
  extra_form_data: {}
  granularity_sqla: notified_mc_date
  groupby:
  - control_failure
  metrics:
  - COUNT
  order_by_cols: []
  order_desc: true
  percent_metrics: []
  query_mode: aggregate
  row_limit: 10000
  server_page_length: 10
  show_cell_bars: false
  show_totals: false
  slice_id: 171
  table_timestamp_format: smart_date
  time_grain_sqla: P1D
  time_range: No filter
  url_params: {}
  viz_type: table
cache_timeout: null
uuid: 0e0b7ac2-7998-ceff-c24b-333fa728bc23
version: 1.0.0
dataset_uuid: f8317c8b-7468-9302-8dd4-bb1298e9d50c
