slice_name: SI - Share Class Filter for Negative Movement
viz_type: filter_box
params:
  adhoc_filters:
  - clause: WHERE
    comparator: '0'
    expressionType: SIMPLE
    filterOptionName: filter_rcsvqh4h1uc_n9o9m5fs1ti
    isExtra: false
    isNew: false
    operator: <
    operatorId: LESS_THAN
    sqlExpression: null
    subject: fund_movement_value
  datasource: 58__table
  date_filter: false
  extra_form_data: {}
  filter_configs:
  - asc: true
    clearable: true
    column: share_class_name
    key: YbePe-1xk
    label: Share Class
    multiple: true
    searchAllOptions: false
  instant_filtering: true
  time_grain_sqla: P1D
  time_range: Last week
  url_params: {}
  viz_type: filter_box
cache_timeout: null
uuid: 6238f28c-c96e-4f04-82de-3bf68e7b54cf
version: 1.0.0
dataset_uuid: c28fef52-923b-a734-0b83-4cec471c48cc
