slice_name: SI - Closed Breach Details
viz_type: table
params:
  adhoc_filters:
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_kkbldzdknn_4nfcqe4bu3w
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: closed_date >= date_trunc('Week',(current_date - INTERVAL '3 weeks'))::date
    subject: null
  all_columns:
  - days_since_closed_txt
  - breach_ref
  - client_ref
  - client_name
  - original_closed_date
  - control_refs
  color_pn: true
  datasource: 48__table
  extra_form_data: {}
  granularity_sqla: closed_date
  groupby: []
  include_search: true
  metrics:
  - count
  order_by_cols:
  - '["days_since_closed_txt", false]'
  order_desc: true
  page_length: 20
  percent_metrics: []
  query_mode: raw
  row_limit: 10000
  server_page_length: 10
  show_cell_bars: false
  slice_id: 177
  table_timestamp_format: smart_date
  time_grain_sqla: P1D
  time_range: No filter
  url_params: {}
  viz_type: table
cache_timeout: null
uuid: 545fa3bf-2be3-2761-72d9-3ca7cceaea95
version: 1.0.0
dataset_uuid: f8317c8b-7468-9302-8dd4-bb1298e9d50c
