slice_name: SI0 - Work Item Filters
viz_type: filter_box
params:
  adhoc_filters:
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_rilsj378iwn_gcm7hpe8f3
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: unitcd like 'METRO%'
    subject: null
  datasource: 7__table
  date_filter: false
  extra_form_data: {}
  filter_configs:
  - asc: true
    clearable: true
    column: owner_department
    key: 0tcxZq4Xq
    label: Department
    multiple: true
    searchAllOptions: false
  - asc: true
    clearable: true
    column: owner_team
    key: iSilDYVeP
    label: Team
    multiple: true
    searchAllOptions: false
  - asc: true
    clearable: true
    column: wrktype
    key: 16FnEdNNN
    label: Work Type
    multiple: true
    searchAllOptions: false
  - asc: true
    clearable: true
    column: processing_stage
    key: NwPXQgBw6
    label: Processing Stage
    multiple: true
    searchAllOptions: false
  - asc: true
    clearable: true
    column: age_bus_days_band
    key: c337m8lN_
    label: Age in Business Days
    multiple: true
    searchAllOptions: false
  - asc: true
    clearable: true
    column: suspend_flag
    key: 2c6OYIbVW
    label: Suspended
    multiple: true
    searchAllOptions: false
  - asc: true
    clearable: true
    column: manual_deal_flag
    key: 2N9KOAxE8
    label: Outstanding Manual Deals
    multiple: true
    searchAllOptions: false
  granularity_sqla: crdate
  instant_filtering: true
  time_grain_sqla: null
  time_range: No filter
  url_params: {}
  viz_type: filter_box
cache_timeout: null
uuid: b50029d2-e650-4fa4-a2bd-184a051662f2
version: 1.0.0
dataset_uuid: fa1cab1e-d9ee-f116-392a-98ac627773a0
