slice_name: SI0 - Complaints Received Filter
viz_type: filter_box
params:
  adhoc_filters: []
  datasource: 15__table
  date_filter: true
  filter_configs:
  - asc: true
    clearable: true
    column: category_group
    key: 1nUl9aasm
    label: Complaint Category Group
    multiple: true
    searchAllOptions: false
  granularity_sqla: received_date
  instant_filtering: true
  queryFields: {}
  time_range: No filter
  url_params: {}
  viz_type: filter_box
cache_timeout: null
uuid: 80105088-f317-af10-fe03-24881e714b77
version: 1.0.0
dataset_uuid: 15464cf9-c639-d9cb-4f5f-eaa791a90ea0
