slice_name: SI2 - Today's Notifiable Deals
viz_type: table
params:
  adhoc_filters:
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_3iixxntydla_s6z971g2nyb
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: RTRIM(transaction_type) <> 'Stock Transfer In'
    subject: null
  - clause: WHERE
    comparator: 'Yes'
    expressionType: SIMPLE
    filterOptionName: filter_7womioxlkuo_japmlk30n9
    isExtra: false
    isNew: false
    operator: ==
    operatorId: EQUALS
    sqlExpression: null
    subject: CURRENT DAY FLAG
  - clause: WHERE
    comparator: Y
    expressionType: SIMPLE
    filterOptionName: filter_006qyvcedxgwn_h3uhons671t
    isExtra: false
    isNew: false
    operator: ==
    operatorId: EQUALS
    sqlExpression: null
    subject: notifiable_deal_flag
  - clause: WHERE
    comparator: N
    expressionType: SIMPLE
    filterOptionName: filter_3fs2affg5b3_xuvg2xngzek
    isExtra: false
    isNew: false
    operator: ==
    operatorId: EQUALS
    sqlExpression: null
    subject: Cancelled
  all_columns:
  - share_class_name
  - fund_code
  - isin_code
  - unitholder_id
  - deal_id
  - Deal Date
  - trade_origin
  - transaction_type
  - Notifiable Transaction Price
  - VP Time
  - '% of Fund'
  - Actual Units
  - Est. Actual Cash
  - Cancelled
  color_pn: false
  column_config:
    '% of Fund':
      d3NumberFormat: ',.2%'
      d3SmallNumberFormat: ',.2%'
    Actual Units:
      d3NumberFormat: ',.4f'
      d3SmallNumberFormat: ',.4f'
    Est. Actual Cash:
      d3NumberFormat: ',.2f'
      d3SmallNumberFormat: ',.2f'
    Notifiable Transaction Price:
      d3NumberFormat: ',.4f'
      d3SmallNumberFormat: ',.4f'
      showCellBars: false
  conditional_formatting: []
  datasource: 76__table
  extra_form_data: {}
  granularity_sqla: null
  groupby: []
  include_search: true
  metrics:
  - count
  order_by_cols: []
  order_desc: true
  percent_metrics: []
  query_mode: raw
  row_limit: 10000
  server_page_length: 10
  show_cell_bars: false
  slice_id: 310
  table_timestamp_format: smart_date
  time_grain_sqla: P1D
  time_range: No filter
  url_params: {}
  viz_type: table
cache_timeout: null
uuid: 985a686f-296f-418e-b348-bf3aae5a4268
version: 1.0.0
dataset_uuid: ebf32c00-65fc-4211-98df-7bbfec2a9c69
