slice_name: SI4 - Deals Exceeding Threshold
viz_type: bar
params:
  adhoc_filters:
  - clause: WHERE
    comparator: N
    expressionType: SIMPLE
    filterOptionName: filter_n8hsbyqato_xsg00b480c
    isExtra: false
    isNew: false
    operator: ==
    operatorId: EQUALS
    sqlExpression: null
    subject: cancelled
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_as9j8lgk6z5_guciuf4hg9o
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: cash_gross_amount <= -50000 or  cash_gross_amount >= 50000
    subject: null
  annotation_layers: []
  bottom_margin: auto
  color_scheme: supersetColors
  comparison_type: values
  datasource: 93__table
  extra_form_data: {}
  granularity_sqla: eff_date
  groupby:
  - Money In/Out
  left_margin: auto
  line_interpolation: linear
  metrics:
  - count distinct deal
  order_desc: true
  rich_tooltip: true
  rolling_type: None
  row_limit: 50000
  show_brush: auto
  show_legend: true
  slice_id: 422
  time_grain_sqla: P1W
  time_range: 'DATEADD(DATETIME("now"), -2, month) : now'
  url_params: {}
  viz_type: bar
  x_axis_format: '%d/%m/%Y'
  x_ticks_layout: auto
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
cache_timeout: null
uuid: 1106f040-2e4f-49a6-834a-68e41a6b56b6
version: 1.0.0
dataset_uuid: 74fa6896-5e25-4630-b057-9f43589743fa
