slice_name: SI - Today's Net Movement
viz_type: big_number_total
params:
  adhoc_filters: []
  datasource: 58__table
  header_font_size: 0.4
  metric: Movement Value Total
  slice_id: 245
  subheader_font_size: 0.15
  time_range: Last week
  url_params: {}
  viz_type: big_number_total
  y_axis_format: SMART_NUMBER
cache_timeout: null
uuid: 3ca9d8e7-75f2-98c9-ebbb-ff790b188daa
version: 1.0.0
dataset_uuid: c28fef52-923b-a734-0b83-4cec471c48cc
