slice_name: Average and Sum Trends
description: null
certified_by: null
certification_details: null
viz_type: dual_line
params:
  compare_lag: '10'
  compare_suffix: o10Y
  granularity_sqla: ds
  groupby: []
  limit: '25'
  markup_type: markdown
  metric:
    aggregate: AVG
    column:
      column_name: num
      type: BIGINT(20)
    expressionType: SIMPLE
    label: AVG(num)
    optionName: metric_vgops097wej_g8uff99zhk7
  metric_2: sum__num
  metrics:
  - aggregate: SUM
    column:
      column_name: num
      type: BIGINT
    expressionType: SIMPLE
    label: Births
    optionName: metric_11
  row_limit: 50000
  time_range: '100 years ago : now'
  viz_type: dual_line
query_context: null
cache_timeout: null
uuid: b62d10b5-e650-4afe-b97d-3f7afdca1dde
version: 1.0.0
dataset_uuid: 29e854db-68af-463f-b0a1-7acd63bfccdd
