slice_name: Box plot
viz_type: box_plot
params:
  compare_lag: '10'
  compare_suffix: o10Y
  country_fieldtype: cca3
  entity: country_code
  granularity_sqla: year
  groupby:
  - region
  limit: '25'
  markup_type: markdown
  metrics:
  - sum__SP_POP_TOTL
  row_limit: 50000
  show_bubbles: true
  since: '1960-01-01'
  time_range: '2014-01-01 : 2014-01-02'
  until: now
  viz_type: box_plot
  whisker_options: Min/max (no outliers)
  x_ticks_layout: staggered
cache_timeout: null
uuid: e51df81d-298d-4c79-bf1b-d1a9ae8e0f4d
version: 1.0.0
dataset_uuid: 7425b821-932d-408a-a7be-3e10a3e463a5
