slice_name: Boy Name Cloud
viz_type: word_cloud
params:
  adhoc_filters:
  - clause: WHERE
    comparator: boy
    expressionType: SIMPLE
    operator: ==
    subject: gender
  compare_lag: '10'
  compare_suffix: o10Y
  granularity_sqla: ds
  groupby: []
  limit: '100'
  markup_type: markdown
  metric: sum__num
  rotation: square
  row_limit: 50000
  series: name
  since: 100 years ago
  size_from: '10'
  size_to: '70'
  time_range: No filter
  until: now
  viz_type: word_cloud
cache_timeout: null
uuid: 8da67bf6-c351-4e52-9c05-9e19f75cf066
version: 1.0.0
dataset_uuid: 2f14b67b-aebd-47af-970c-83258a649d99
