slice_name: Boys
viz_type: table
params:
  adhoc_filters:
  - clause: WHERE
    comparator: boy
    expressionType: SIMPLE
    operator: ==
    subject: gender
  compare_lag: '10'
  compare_suffix: o10Y
  granularity_sqla: ds
  groupby:
  - name
  limit: '25'
  markup_type: markdown
  metrics:
  - sum__num
  row_limit: 50
  since: 100 years ago
  time_range: No filter
  timeseries_limit_metric: sum__num
  until: now
  viz_type: table
cache_timeout: null
uuid: c9155f69-02e7-46f3-9063-5586546f8148
version: 1.0.0
dataset_uuid: 6c27ef42-7425-406c-b19c-c3b043b19a99
