slice_name: Daily Totals
viz_type: table
params:
  compare_lag: '10'
  compare_suffix: o10Y
  granularity_sqla: ds
  groupby:
  - ds
  limit: '25'
  markup_type: markdown
  metrics:
  - aggregate: SUM
    column:
      column_name: num
      type: BIGINT
    expressionType: SIMPLE
    label: Births
    optionName: metric_11
  row_limit: 50000
  since: 40 years ago
  time_range: No filter
  until: now
  viz_type: table
cache_timeout: null
uuid: 2cb1e35a-f4a9-41d2-8a7f-d285eb82c4c8
version: 1.0.0
dataset_uuid: 2f14b67b-aebd-47af-970c-83258a649d99
