slice_name: Deck.gl Screen grid
viz_type: deck_screengrid
params:
  color_picker:
    a: 1
    b: 0
    g: 255
    r: 14
  datasource: 5__table
  granularity_sqla: null
  grid_size: 20
  groupby: []
  mapbox_style: mapbox://styles/mapbox/dark-v9
  point_radius: Auto
  point_radius_fixed:
    type: fix
    value: 2000
  point_unit: square_m
  row_limit: 5000
  size: count
  spatial:
    latCol: LAT
    lonCol: LON
    type: latlong
  time_grain_sqla: null
  time_range: No filter
  viewport:
    bearing: -4.952916738791771
    latitude: 37.76024135844065
    longitude: -122.41827069521386
    pitch: 4.750411100577438
    zoom: 14.161641703941438
  viz_type: deck_screengrid
cache_timeout: null
uuid: cc70f6a6-5339-4788-b2cc-0ab6d7731a6e
version: 1.0.0
dataset_uuid: ce9d35cd-326e-4001-a6ac-fbe42d5243fc
