slice_name: FMR - UHS - Number of accounts opened
viz_type: big_number_total
params:
  adhoc_filters: []
  datasource: 54__table
  granularity_sqla: latest_valuation_date
  header_font_size: 0.4
  metric:
    aggregate: COUNT_DISTINCT
    column:
      column_name: acc_id
      description: Account ID from GDP
      expression: null
      filterable: true
      groupby: true
      id: 864
      is_dttm: false
      python_date_format: null
      type: INTEGER
      verbose_name: null
    expressionType: SIMPLE
    hasCustomLabel: false
    isNew: false
    label: COUNT_DISTINCT(acc_id)
    optionName: metric_1e6nn3awaxb_rj7k7un5mj
    sqlExpression: null
  queryFields:
    metric: metrics
  slice_id: 214
  subheader: Accounts Opened
  subheader_font_size: 0.15
  time_range: No filter
  url_params: {}
  viz_type: big_number_total
  y_axis_format: SMART_NUMBER
cache_timeout: null
uuid: cb4a523d-3581-1cb8-0f60-5c70ed30da4a
version: 1.0.0
dataset_uuid: 294bb475-bd97-fe6c-dec6-ec4cd42fc6fa
