slice_name: FMR - UHS - IVC Split Value
description: null
certified_by: null
certification_details: null
viz_type: dist_bar
params:
  adhoc_filters:
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_o6uzvhva8ue_z2m5j8qrhh
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: units_unsett_est+units_unsett_act+units_sett<>0
    subject: null
  bar_stacked: true
  bottom_margin: auto
  color_scheme: supersetColors
  columns:
  - ccy_id
  contribution: false
  datasource: 54__table
  granularity_sqla: latest_valuation_date
  groupby:
  - ivc_long_name
  label_colors: {}
  metrics:
  - aggregate: null
    column: null
    expressionType: SQL
    hasCustomLabel: true
    isNew: false
    label: Total Value of Units Held
    optionName: metric_08vb84mhphcv_au3fid6nejq
    sqlExpression: SUM((units_unsett_est+units_unsett_act+units_sett)*latest_price_amount)
  queryFields:
    columns: groupby
    groupby: groupby
    metrics: metrics
  reduce_x_ticks: false
  row_limit: null
  show_bar_value: false
  show_legend: true
  slice_id: 211
  time_range: No filter
  url_params: {}
  viz_type: dist_bar
  x_ticks_layout: auto
  y_axis_format: SMART_NUMBER
query_context: null
cache_timeout: null
uuid: 689af06b-94ef-fe4e-98e4-c074dede75f9
version: 1.0.0
dataset_uuid: 294bb475-bd97-fe6c-dec6-ec4cd42fc6fa
