slice_name: FMR - UHS - Investor Summary
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters: []
  all_columns: []
  color_pn: false
  datasource: 54__table
  granularity_sqla: latest_valuation_date
  groupby:
  - client_number
  - investor_typ_txt
  - salutation
  - gdr_description
  - client_language
  - cty_description
  - crr_description
  - investor_age
  metrics: null
  order_by_cols: []
  order_desc: true
  page_length: 0
  percent_metrics: []
  queryFields:
    groupby: groupby
    metrics: metrics
  query_mode: aggregate
  row_limit: '2'
  show_cell_bars: false
  slice_id: 212
  table_timestamp_format: smart_date
  time_grain_sqla: P1D
  time_range: No filter
  url_params: {}
  viz_type: table
query_context: null
cache_timeout: null
uuid: b83fa251-d642-a314-c47d-a7e99b26be7d
version: 1.0.0
dataset_uuid: 294bb475-bd97-fe6c-dec6-ec4cd42fc6fa
