slice_name: FMR - FFS - Filter
description: null
certified_by: null
certification_details: null
viz_type: filter_box
params:
  adhoc_filters: []
  datasource: 59__table
  date_filter: true
  filter_configs:
  - asc: true
    clearable: true
    column: ivh_description
    key: aBQPtXfzg
    label: Fund
    multiple: true
    searchAllOptions: false
  - asc: true
    clearable: true
    column: txnt_description
    key: HBDlYXVQ7
    label: Transaction type
    multiple: true
    searchAllOptions: false
  granularity_sqla: transaction_date
  instant_filtering: false
  show_sqla_time_column: false
  show_sqla_time_granularity: false
  slice_id: 273
  time_grain_sqla: P1D
  time_range: No filter
  url_params: {}
  viz_type: filter_box
query_context: null
cache_timeout: null
uuid: ad39f33b-a594-d180-dfb0-572683f85d8c
version: 1.0.0
dataset_uuid: 7120d902-3388-b051-9a3f-c4eab9125168
