slice_name: "FMR - FBS \u2013 Date Filters"
description: null
certified_by: null
certification_details: null
viz_type: filter_box
params:
  adhoc_filters: []
  datasource: 45__table
  date_filter: false
  filter_configs:
  - asc: false
    clearable: true
    column: valuation_date_txt_jinja
    defaultValue: ''
    key: 4Ifx1DV_l
    label: Valuation date
    multiple: false
    searchAllOptions: false
  - asc: true
    clearable: true
    column: vp_cutoff_with_timezone_jinja
    defaultValue: ''
    key: LsRnELEbV
    label: VP Cutoff
    multiple: true
    searchAllOptions: false
  granularity_sqla: valuation_date
  instant_filtering: true
  show_druid_time_granularity: false
  show_druid_time_origin: false
  show_sqla_time_column: false
  show_sqla_time_granularity: false
  slice_id: 131
  time_grain_sqla: P1D
  time_range: No filter
  url_params: {}
  viz_type: filter_box
query_context: null
cache_timeout: null
uuid: 266ee7b9-1556-e2d1-5734-27269d63f31a
version: 1.0.0
dataset_uuid: 684545bb-cddf-d2d0-9669-f67301bffd4e
