slice_name: Girl Name Cloud
description: null
certified_by: null
certification_details: null
viz_type: word_cloud
params:
  adhoc_filters:
  - clause: WHERE
    comparator: girl
    expressionType: SIMPLE
    operator: ==
    subject: gender
  compare_lag: '10'
  compare_suffix: o10Y
  granularity_sqla: ds
  groupby: []
  limit: '100'
  markup_type: markdown
  metric: sum__num
  rotation: square
  row_limit: 50000
  series: name
  size_from: '10'
  size_to: '70'
  time_range: '100 years ago : now'
  viz_type: word_cloud
query_context: null
cache_timeout: null
uuid: 0ddf7513-3547-439f-8e26-7a7b6b8594ac
version: 1.0.0
dataset_uuid: 29e854db-68af-463f-b0a1-7acd63bfccdd
