slice_name: Girl Name Cloud
viz_type: word_cloud
params:
  adhoc_filters:
  - clause: WHERE
    comparator: girl
    expressionType: SIMPLE
    operator: ==
    subject: gender
  compare_lag: '10'
  compare_suffix: o10Y
  granularity_sqla: ds
  groupby: []
  limit: '100'
  markup_type: markdown
  metric: sum__num
  rotation: square
  row_limit: 50000
  series: name
  since: 100 years ago
  size_from: '10'
  size_to: '70'
  time_range: No filter
  until: now
  viz_type: word_cloud
cache_timeout: null
uuid: e426a317-eeaf-4a50-9330-3a60a221127a
version: 1.0.0
dataset_uuid: 6c27ef42-7425-406c-b19c-c3b043b19a99
