slice_name: Growth Rate
viz_type: line
params:
  compare_lag: '10'
  compare_suffix: o10Y
  country_fieldtype: cca3
  entity: country_code
  granularity_sqla: year
  groupby:
  - country_name
  limit: '25'
  markup_type: markdown
  metrics:
  - sum__SP_POP_TOTL
  num_period_compare: '10'
  row_limit: 50000
  show_bubbles: true
  since: '1960-01-01'
  time_range: '2014-01-01 : 2014-01-02'
  until: '2014-01-02'
  viz_type: line
cache_timeout: null
uuid: 7f28fd95-e440-4214-814a-45a7868950e8
version: 1.0.0
dataset_uuid: 1d2a104d-5d12-4666-874f-c991ec5c9130
