slice_name: Life Expectancy VS Rural %
viz_type: bubble
params:
  adhoc_filters:
  - clause: WHERE
    comparator:
    - TCA
    - MNP
    - DMA
    - MHL
    - MCO
    - SXM
    - CYM
    - TUV
    - IMY
    - KNA
    - ASM
    - ADO
    - AMA
    - PLW
    expressionType: SIMPLE
    filterOptionName: 2745eae5
    operator: NOT IN
    subject: country_code
  compare_lag: '10'
  compare_suffix: o10Y
  country_fieldtype: cca3
  entity: country_name
  granularity_sqla: year
  groupby: []
  limit: 0
  markup_type: markdown
  max_bubble_size: '50'
  row_limit: 50000
  series: region
  show_bubbles: true
  since: '2011-01-01'
  size: sum__SP_POP_TOTL
  time_range: '2014-01-01 : 2014-01-02'
  until: '2011-01-02'
  viz_type: bubble
  x: sum__SP_RUR_TOTL_ZS
  y: sum__SP_DYN_LE00_IN
cache_timeout: null
uuid: 86216d79-a2f3-460a-9ae8-e3142fae145a
version: 1.0.0
dataset_uuid: 8ed131ea-0048-485f-88de-6105e7422210
