slice_name: Mockup for SI UK - AML Trades from customers in high risk countries
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters: []
  all_columns:
  - deal_date
  - deal_id
  - unitholder_id
  - client_name
  - client_category
  - sale_or_repurchase
  - client_type
  - risk_rating
  color_pn: true
  conditional_formatting: []
  datasource: 95__table
  extra_form_data: {}
  granularity_sqla: deal_date
  groupby:
  - deal_date
  order_by_cols: []
  order_desc: true
  percent_metrics: []
  query_mode: raw
  row_limit: 10000
  server_page_length: 10
  show_cell_bars: true
  slice_id: 2000000022
  table_timestamp_format: smart_date
  time_grain_sqla: P1D
  time_range: No filter
  url_params: {}
  viz_type: table
query_context: null
cache_timeout: null
uuid: c0b3c645-97be-476f-8023-302cfdf8390b
version: 1.0.0
dataset_uuid: 1f183292-9794-4769-b7a7-a08acfeb402a
