slice_name: Most Populated Countries
viz_type: table
params:
  compare_lag: '10'
  compare_suffix: o10Y
  country_fieldtype: cca3
  entity: country_code
  granularity_sqla: year
  groupby:
  - country_name
  limit: '25'
  markup_type: markdown
  metrics:
  - sum__SP_POP_TOTL
  row_limit: 50000
  show_bubbles: true
  since: '2014-01-01'
  time_range: '2014-01-01 : 2014-01-02'
  until: '2014-01-02'
  viz_type: table
cache_timeout: null
uuid: b86ea10c-0a2a-4520-bf67-5e296b091952
version: 1.0.0
dataset_uuid: 8ed131ea-0048-485f-88de-6105e7422210
