slice_name: Names Sorted by Num in California
viz_type: table
params:
  compare_lag: '10'
  compare_suffix: o10Y
  granularity_sqla: ds
  groupby:
  - name
  limit: '25'
  markup_type: markdown
  metrics:
  - aggregate: SUM
    column:
      column_name: num
      type: BIGINT
    expressionType: SIMPLE
    label: Births
    optionName: metric_11
  row_limit: 50
  since: 100 years ago
  time_range: No filter
  timeseries_limit_metric:
    aggregate: SUM
    column:
      column_name: num_california
      expression: CASE WHEN state = 'CA' THEN num ELSE 0 END
    expressionType: SIMPLE
    label: SUM(num_california)
  until: now
  viz_type: table
cache_timeout: null
uuid: 0dbe6773-31d4-45cb-a125-fa589bd41812
version: 1.0.0
dataset_uuid: 5f4d9b3a-846b-4ae1-adc6-4bcb1cf5bcc9
