slice_name: Num Births Trend
viz_type: line
params:
  compare_lag: '10'
  compare_suffix: o10Y
  granularity_sqla: ds
  groupby: []
  limit: '25'
  markup_type: markdown
  metrics:
  - aggregate: SUM
    column:
      column_name: num
      type: BIGINT
    expressionType: SIMPLE
    label: Births
    optionName: metric_11
  row_limit: 50000
  since: 100 years ago
  time_range: No filter
  until: now
  viz_type: line
cache_timeout: null
uuid: 014ced78-195b-4101-981e-4c4da31d143c
version: 1.0.0
dataset_uuid: 6c27ef42-7425-406c-b19c-c3b043b19a99
