slice_name: Number of California Births
viz_type: big_number_total
params:
  compare_lag: '10'
  compare_suffix: o10Y
  granularity_sqla: ds
  groupby: []
  limit: '25'
  markup_type: markdown
  metric:
    aggregate: SUM
    column:
      column_name: num_california
      expression: CASE WHEN state = 'CA' THEN num ELSE 0 END
    expressionType: SIMPLE
    label: SUM(num_california)
  row_limit: 50000
  since: 100 years ago
  time_range: No filter
  until: now
  viz_type: big_number_total
cache_timeout: null
uuid: bb88b9a8-b57f-40be-89e4-66a6673f6e61
version: 1.0.0
dataset_uuid: 77361041-c96a-4c59-87fe-8730f9a6ddb1
