slice_name: Parallel Coordinates
viz_type: para
params:
  compare_lag: '10'
  compare_suffix: o10Y
  country_fieldtype: cca3
  entity: country_code
  granularity_sqla: year
  groupby: []
  limit: 100
  markup_type: markdown
  metrics:
  - sum__SP_POP_TOTL
  - sum__SP_RUR_TOTL_ZS
  - sum__SH_DYN_AIDS
  row_limit: 50000
  secondary_metric: sum__SP_POP_TOTL
  series: country_name
  show_bubbles: true
  since: '2011-01-01'
  time_range: '2014-01-01 : 2014-01-02'
  until: '2012-01-01'
  viz_type: para
cache_timeout: null
uuid: 93fc27b3-252e-4d0d-bba4-d65edafec52a
version: 1.0.0
dataset_uuid: 7425b821-932d-408a-a7be-3e10a3e463a5
