slice_name: Participants
viz_type: big_number
params:
  compare_lag: '5'
  compare_suffix: over 5Y
  granularity_sqla: ds
  groupby: []
  limit: '25'
  markup_type: markdown
  metric: sum__num
  row_limit: 50000
  since: 100 years ago
  time_range: No filter
  until: now
  viz_type: big_number
cache_timeout: null
uuid: a8987cf3-097f-4226-964a-347b177b75dc
version: 1.0.0
dataset_uuid: 2f14b67b-aebd-47af-970c-83258a649d99
