slice_name: Pivot Table v2
viz_type: pivot_table_v2
params:
  compare_lag: '10'
  compare_suffix: o10Y
  granularity_sqla: ds
  groupby: []
  groupbyColumns:
  - state
  groupbyRows:
  - name
  limit: '25'
  markup_type: markdown
  metrics:
  - sum__num
  row_limit: 50000
  since: 100 years ago
  time_range: No filter
  until: now
  viz_type: pivot_table_v2
cache_timeout: null
uuid: 0b4a95c0-bfcf-4b41-8b8f-c081d74d8c32
version: 1.0.0
dataset_uuid: 6c27ef42-7425-406c-b19c-c3b043b19a99
