slice_name: POC - AWD Table
viz_type: table
params:
  adhoc_filters:
  - clause: WHERE
    comparator: null
    expressionType: SIMPLE
    filterOptionName: filter_idnuzamt2t_a5ldc12mqgr
    isExtra: false
    isNew: false
    operator: IS NOT NULL
    operatorId: IS_NOT_NULL
    sqlExpression: null
    subject: Parent Entity
  - clause: WHERE
    comparator: null
    expressionType: SIMPLE
    filterOptionName: filter_q9asbywmwx_rs1x2u31m0t
    isExtra: false
    isNew: false
    operator: IS NOT NULL
    operatorId: IS_NOT_NULL
    sqlExpression: null
    subject: Client
  all_columns: []
  color_pn: true
  datasource: 2000000004__table
  extra_form_data: {}
  granularity_sqla: last_update_dattim
  groupby:
  - Parent Entity
  - Client
  metrics:
  - count
  order_by_cols: []
  order_desc: true
  percent_metrics: []
  query_mode: aggregate
  row_limit: 10000
  server_page_length: 10
  show_cell_bars: true
  table_timestamp_format: smart_date
  time_grain_sqla: P1D
  time_range: No filter
  url_params: {}
  viz_type: table
cache_timeout: null
uuid: 04de72f9-42b7-45ee-a852-fe48f6497286
version: 1.0.0
dataset_uuid: a2979166-4c9b-409b-93d1-b92b6a3d39ad
