slice_name: Rural Breakdown
viz_type: sunburst
params:
  compare_lag: '10'
  compare_suffix: o10Y
  country_fieldtype: cca3
  entity: country_code
  granularity_sqla: year
  groupby:
  - region
  - country_name
  limit: '25'
  markup_type: markdown
  metric: sum__SP_POP_TOTL
  row_limit: 50000
  secondary_metric:
    aggregate: SUM
    column:
      column_name: SP_RUR_TOTL
      optionName: _col_SP_RUR_TOTL
      type: DOUBLE
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Rural Population
  show_bubbles: true
  since: '2011-01-01'
  time_range: '2014-01-01 : 2014-01-02'
  until: '2011-01-02'
  viz_type: sunburst
cache_timeout: null
uuid: 1a430550-6b00-401e-8a07-a3fd1e66ea52
version: 1.0.0
dataset_uuid: 7425b821-932d-408a-a7be-3e10a3e463a5
