slice_name: SI0 - Non-END Referred Work Items
viz_type: table
params:
  adhoc_filters:
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_jgdqei9u0ob_gu30gxe2uws
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: unitcd in ('METROGBP','METROEUR','METROUSD')
    subject: null
  - clause: WHERE
    comparator: '''Management Company Refer'''
    expressionType: SIMPLE
    filterOptionName: filter_rw22xfftpgl_bh2veathx6n
    isExtra: false
    isNew: false
    operator: ==
    sqlExpression: null
    subject: owner_team
  all_columns:
  - crdattim
  - unitcd
  - wrktype
  - processing_stage
  - suspend_flag
  - age_bus_days
  - uh_id
  - agent_id
  color_pn: true
  datasource: 7__table
  extra_form_data: {}
  granularity_sqla: crdate
  groupby: []
  include_search: true
  metrics:
  - count
  order_by_cols: []
  order_desc: true
  page_length: 10
  percent_metrics: []
  query_mode: raw
  row_limit: 10000
  server_page_length: 10
  show_cell_bars: false
  slice_id: 29
  table_timestamp_format: smart_date
  time_grain_sqla: null
  time_range: No filter
  url_params: {}
  viz_type: table
cache_timeout: null
uuid: af37ff23-9214-a852-4ae1-dede082884ba
version: 1.0.0
dataset_uuid: fa1cab1e-d9ee-f116-392a-98ac627773a0
