slice_name: SI0 - Today's Deals Filter
description: null
certified_by: null
certification_details: null
viz_type: filter_box
params:
  adhoc_filters: []
  datasource: 11__table
  date_filter: false
  filter_configs:
  - asc: true
    clearable: true
    column: investment_vehicle_class
    key: Hios8due6
    label: Share Class
    multiple: true
    searchAllOptions: false
  instant_filtering: true
  queryFields: {}
  time_range: Last week
  url_params: {}
  viz_type: filter_box
query_context: '{"datasource":{"id":11,"type":"table"},"force":false,"queries":[{"time_range":"Last
  week","filters":[],"extras":{"having":"","having_druid":[],"where":""},"applied_time_extras":{},"columns":[],"metrics":[],"annotation_layers":[],"timeseries_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: a1bd59b6-cacb-feee-dd13-44e0e8f434dd
version: 1.0.0
dataset_uuid: c60b9c13-4af3-3897-b341-d1e673bdc36a
