slice_name: SI0 - Voided Breach details
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters: []
  align_pn: false
  all_columns:
  - Age
  - breach_ref
  - client_id
  - client_name
  - original_void_date
  - breach_control_ref
  color_pn: true
  datasource: 18__table
  granularity_sqla: original_void_date
  groupby: []
  include_search: true
  metrics:
  - count
  order_by_cols:
  - '["Age", false]'
  order_desc: true
  page_length: 20
  percent_metrics: []
  queryFields:
    groupby: groupby
    metrics: metrics
  query_mode: raw
  row_limit: 10000
  show_cell_bars: true
  slice_id: 75
  table_timestamp_format: '%d-%b-%Y'
  time_grain_sqla: P1D
  time_range: No filter
  url_params: {}
  viz_type: table
query_context: null
cache_timeout: null
uuid: e0f2f214-bcf2-4db5-9b75-799233291ea1
version: 1.0.0
dataset_uuid: 1fb22064-3ea8-0f84-e94e-98f1c002ab5a
