slice_name: SI0 - Outstanding Items by Department
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters:
  - clause: WHERE
    comparator: METRO%
    expressionType: SIMPLE
    filterOptionName: filter_le7bf5e1yp_tsm9mmz8wbf
    isExtra: false
    isNew: false
    operator: LIKE
    sqlExpression: null
    subject: unitcd
  all_columns: []
  color_pn: true
  datasource: 7__table
  extra_form_data: {}
  granularity_sqla: crdate
  groupby:
  - owner_department
  metrics:
  - count
  order_by_cols: []
  order_desc: true
  page_length: 0
  percent_metrics: []
  query_mode: aggregate
  row_limit: 10000
  server_page_length: 10
  show_cell_bars: false
  table_timestamp_format: smart_date
  time_grain_sqla: P1D
  time_range: No filter
  url_params: {}
  viz_type: table
query_context: null
cache_timeout: null
uuid: d23d1588-41c1-47a3-a808-4813f753c10c
version: 1.0.0
dataset_uuid: fa1cab1e-d9ee-f116-392a-98ac627773a0
