slice_name: SI0 - Percentage of significant breaches
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters: []
  all_columns: []
  color_pn: true
  column_config:
    Total Number of Breaches:
      showCellBars: false
  conditional_formatting: []
  datasource: 19__table
  extra_form_data: {}
  granularity_sqla: manco_notified_date
  groupby:
  - Significance
  metrics:
  - Total Number of Breaches
  order_by_cols: []
  order_desc: true
  percent_metrics: []
  query_mode: aggregate
  row_limit: 10000
  server_page_length: 10
  show_cell_bars: false
  slice_id: 56
  table_timestamp_format: smart_date
  time_grain_sqla: P1D
  time_range: No filter
  url_params: {}
  viz_type: table
query_context: null
cache_timeout: null
uuid: 0678c6b9-145c-4976-85f1-c6e87497aa16
version: 1.0.0
dataset_uuid: 2c547240-669b-1566-c497-e9841401ead7
