slice_name: SI0 - Assets Under Management
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  adhoc_filters: []
  datasource: 22__table
  header_font_size: 0.4
  metric:
    aggregate: SUM
    column:
      column_name: last_fund_value
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 349
      is_dttm: false
      optionName: _col_last_fund_value
      python_date_format: null
      type: BIGINT
      verbose_name: null
    expressionType: SIMPLE
    hasCustomLabel: false
    isNew: false
    label: SUM(last_fund_value)
    optionName: metric_fpqmqtdkj88_lfdc74s0n2
    sqlExpression: null
  slice_id: 60
  subheader_font_size: 0.15
  time_range: Last week
  url_params: {}
  viz_type: big_number_total
  y_axis_format: SMART_NUMBER
query_context: '{"datasource":{"id":22,"type":"table"},"force":false,"queries":[{"time_range":"Last
  week","filters":[],"extras":{"having":"","having_druid":[],"where":""},"applied_time_extras":{},"columns":[],"metrics":[{"aggregate":"SUM","column":{"column_name":"last_fund_value","description":null,"expression":null,"filterable":true,"groupby":true,"id":349,"is_dttm":false,"optionName":"_col_last_fund_value","python_date_format":null,"type":"BIGINT","verbose_name":null},"expressionType":"SIMPLE","hasCustomLabel":false,"isNew":false,"label":"SUM(last_fund_value)","optionName":"metric_fpqmqtdkj88_lfdc74s0n2","sqlExpression":null}],"annotation_layers":[],"timeseries_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 7febfac0-2e7e-1e74-e4c6-dd0955f44bcd
version: 1.0.0
dataset_uuid: 3e94bcc8-a638-d77c-5141-f6089ec157c4
