slice_name: SI0 - Notifiable Deals
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters: []
  all_columns:
  - transaction_type_desc
  - Est. Actual Cash
  color_pn: false
  datasource: 10__table
  groupby: []
  metrics:
  - count
  order_by_cols:
  - '["time_of_deal", false]'
  order_desc: true
  page_length: 0
  percent_metrics: []
  query_mode: raw
  row_limit: 10000
  show_cell_bars: false
  slice_id: 34
  table_timestamp_format: smart_date
  time_grain_sqla: P1D
  time_range: No filter
  url_params: {}
  viz_type: table
query_context: null
cache_timeout: null
uuid: 4a7de94e-ce05-6337-0220-30cdf52a10fa
version: 1.0.0
dataset_uuid: 74c45b17-e480-1bd2-7d29-9583f81346c6
