slice_name: SI0 - Largest Negative Fund Movement by %
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  adhoc_filters: []
  datasource: 24__table
  header_font_size: 0.4
  metric: Largest Negative Movement Percent
  slice_id: 65
  subheader_font_size: 0.15
  time_range: Last week
  url_params: {}
  viz_type: big_number_total
  y_axis_format: .3%
query_context: null
cache_timeout: null
uuid: 176c42fe-4ba4-05cb-508c-b74b29e82858
version: 1.0.0
dataset_uuid: 20e76911-9eef-cdc5-25b3-223b1a47ac35
