slice_name: SI0 - Largest Positive Fund Movement by %
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  adhoc_filters: []
  datasource: 24__table
  header_font_size: 0.4
  metric: Largest Positive Movement Percent
  slice_id: 64
  subheader_font_size: 0.15
  time_range: Last week
  url_params: {}
  viz_type: big_number_total
  y_axis_format: .3%
query_context: null
cache_timeout: null
uuid: 0a69be9b-f79f-a293-6c62-b0536ac45036
version: 1.0.0
dataset_uuid: 20e76911-9eef-cdc5-25b3-223b1a47ac35
