slice_name: SI0 - Complaints by Category
viz_type: table
params:
  adhoc_filters: []
  all_columns: []
  color_pn: true
  datasource: 12__table
  groupby:
  - comp_category
  metrics:
  - Number of Complaints
  order_by_cols: []
  order_desc: true
  percent_metrics: []
  queryFields:
    groupby: groupby
    metrics: metrics
  query_mode: aggregate
  row_limit: 10000
  show_cell_bars: true
  table_timestamp_format: smart_date
  time_grain_sqla: P1D
  time_range: Last week
  timeseries_limit_metric: Number of Complaints
  url_params: {}
  viz_type: table
cache_timeout: null
uuid: 17be0909-e75f-f83a-0a29-370d45932902
version: 1.0.0
dataset_uuid: 69e301fa-a835-ac1c-ae96-a6372bbed5e9
