slice_name: SI0 - Part 2(s) to be notified
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  adhoc_filters:
  - clause: WHERE
    comparator: '"Part 2"'
    expressionType: SIMPLE
    filterOptionName: filter_sz9f5iwnbx_hwcal5k69yj
    isExtra: false
    isNew: false
    operator: ==
    sqlExpression: null
    subject: Part_Outstanding
  datasource: 20__table
  extra_form_data: {}
  granularity_sqla: manco_notified_date
  header_font_size: 0.4
  metric: count
  slice_id: 51
  subheader: ''
  subheader_font_size: 0.15
  time_format: '%d-%m-%Y %H:%M:%S'
  time_range: No filter
  url_params: {}
  viz_type: big_number_total
  y_axis_format: SMART_NUMBER
query_context: null
cache_timeout: null
uuid: 4264d440-7171-a6f5-575d-0a32a48c0641
version: 1.0.0
dataset_uuid: e86bd959-0878-588a-29d9-31157bd1370b
