slice_name: SI0 - Referred Work Items
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  adhoc_filters:
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_vzf0ykx9a4s_y280qrm3aer
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: unitcd like 'METRO%'
    subject: null
  - clause: WHERE
    comparator: Management Company Refer
    expressionType: SIMPLE
    filterOptionName: filter_kd3paqspas_dakrsoo4vmm
    isExtra: false
    isNew: false
    operator: ==
    sqlExpression: null
    subject: owner_team
  datasource: 7__table
  extra_form_data: {}
  granularity_sqla: crdate
  header_font_size: 0.4
  metric: count
  slice_id: 33
  subheader: ''
  subheader_font_size: 0.125
  time_format: '%d-%m-%Y %H:%M:%S'
  time_range: No filter
  url_params: {}
  viz_type: big_number_total
  y_axis_format: ~g
query_context: null
cache_timeout: null
uuid: 34cfc5c1-5acb-fae7-6f10-b0a2ed79b347
version: 1.0.0
dataset_uuid: fa1cab1e-d9ee-f116-392a-98ac627773a0
