slice_name: SI0 - Today's Deals
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters: []
  all_columns:
  - deal_ref
  - unitholder
  - client_name
  - agent_name
  - transaction_seq
  - investment_vehicle_class
  - transaction_type
  - transaction_price_status
  - transaction_price
  - Unit Amount
  - Cash Gross Amount
  color_pn: true
  datasource: 11__table
  groupby: []
  include_search: true
  metrics:
  - count
  order_by_cols: []
  order_desc: true
  page_length: 10
  percent_metrics: []
  query_mode: raw
  row_limit: 10000
  show_cell_bars: false
  slice_id: 26
  table_timestamp_format: smart_date
  time_grain_sqla: P1D
  time_range: Last week
  url_params: {}
  viz_type: table
query_context: null
cache_timeout: null
uuid: eae59546-58f1-d837-cc37-2b824a6668c0
version: 1.0.0
dataset_uuid: c60b9c13-4af3-3897-b341-d1e673bdc36a
