slice_name: SI2 - Today's Negative Net Movements
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters:
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_t5wnglmfjn_sota6dnxy8e
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: fund_movement_value < 0
    subject: null
  all_columns:
  - share_class_name
  - fund_movement_percent
  color_pn: false
  column_config:
    fund_movement_percent:
      d3NumberFormat: .2%
      d3SmallNumberFormat: .2%
      showCellBars: false
  conditional_formatting: []
  datasource: 68__table
  extra_form_data: {}
  groupby: []
  include_search: true
  metrics:
  - count
  order_by_cols:
  - '["Today''s Movement %", true]'
  order_desc: true
  page_length: 10
  percent_metrics: []
  query_mode: raw
  row_limit: 10000
  server_page_length: 10
  show_cell_bars: false
  slice_id: 302
  table_timestamp_format: smart_date
  time_grain_sqla: P1D
  time_range: Last week
  url_params: {}
  viz_type: table
query_context: null
cache_timeout: null
uuid: 6ba96502-154f-49cc-b3f7-5193e910ffbf
version: 1.0.0
dataset_uuid: 7d4a695f-2ab8-44e6-9b87-4dd909ab175d
