slice_name: SI2 - Today's Trading
description: Version 1.0 (07-03-2022) CDIG002 Confidential
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters:
  - clause: WHERE
    comparator: 'Yes'
    expressionType: SIMPLE
    filterOptionName: filter_tn4eh122dxp_9slk7zer6vb
    isExtra: false
    isNew: false
    operator: ==
    operatorId: EQUALS
    sqlExpression: null
    subject: CURRENT DAY FLAG
  - clause: WHERE
    comparator: N
    expressionType: SIMPLE
    filterOptionName: filter_cuis94g9og7_mqih4514w5
    isExtra: false
    isNew: false
    operator: ==
    operatorId: EQUALS
    sqlExpression: null
    subject: Cancelled
  all_columns: []
  color_pn: true
  column_config:
    STP Gross Amount:
      showCellBars: false
    STP Gross Amount Neg:
      showCellBars: false
    STP Gross Amount Pos:
      showCellBars: false
    count:
      d3NumberFormat: ',d'
      d3SmallNumberFormat: ',d'
      showCellBars: false
  conditional_formatting: []
  datasource: 76__table
  extra_form_data: {}
  granularity_sqla: null
  groupby:
  - trade_origin
  metrics:
  - STP Gross Amount Pos
  - STP Gross Amount Neg
  - STP Gross Amount
  - count
  order_by_cols: []
  order_desc: true
  percent_metrics: []
  query_mode: aggregate
  row_limit: 10000
  server_page_length: 10
  show_cell_bars: true
  slice_id: 348
  table_timestamp_format: smart_date
  time_grain_sqla: P1D
  time_range: No filter
  url_params: {}
  viz_type: table
query_context: null
cache_timeout: null
uuid: 006fe6d3-a326-4a11-b2ad-5b1cbfaf18eb
version: 1.0.0
dataset_uuid: ebf32c00-65fc-4211-98df-7bbfec2a9c69
