slice_name: SI2 - Fund & Share Class Filter
viz_type: filter_box
params:
  adhoc_filters: []
  datasource: 68__table
  date_filter: false
  filter_configs:
  - asc: true
    clearable: true
    column: share_class_name
    key: ZuIy7LxWN
    multiple: true
    searchAllOptions: false
  instant_filtering: true
  slice_id: 300
  time_grain_sqla: P1D
  time_range: Last week
  url_params: {}
  viz_type: filter_box
cache_timeout: null
uuid: 8b2129da-6323-4a82-869d-c6dc3f387cbd
version: 1.0.0
dataset_uuid: 7d4a695f-2ab8-44e6-9b87-4dd909ab175d
