slice_name: SI2 - Largest Positive Movement by Value
description: Version 1.0 (21-07-2021) CDIG002 Confidential
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  adhoc_filters: []
  datasource: 68__table
  header_font_size: 0.4
  metric: Largest Pos Movement Value
  subheader_font_size: 0.15
  time_range: Last week
  url_params: {}
  viz_type: big_number_total
  y_axis_format: .3s
query_context: null
cache_timeout: null
uuid: f9927523-0527-45c3-b077-ceb2eb51b33c
version: 1.0.0
dataset_uuid: 7d4a695f-2ab8-44e6-9b87-4dd909ab175d
