slice_name: SI2 - NAV Status
description: Version 1.0 (21-07-2021) CDIG002 Confidential
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters: []
  all_columns:
  - fund_name
  - fund_code
  - isin_code
  - share_class_name
  - Latest Price
  - currency
  color_pn: false
  column_config:
    Latest Price:
      d3NumberFormat: ',.4f'
      d3SmallNumberFormat: ',.4f'
  conditional_formatting: []
  datasource: 68__table
  extra_form_data: {}
  groupby: []
  include_search: true
  metrics:
  - count
  order_by_cols: []
  order_desc: true
  page_length: 10
  percent_metrics: []
  query_mode: raw
  row_limit: 1000
  server_page_length: 10
  show_cell_bars: false
  slice_id: 312
  table_timestamp_format: smart_date
  time_grain_sqla: P1D
  time_range: No filter
  url_params: {}
  viz_type: table
query_context: null
cache_timeout: null
uuid: 5a3550cc-7130-4de2-a087-3f8e650d626f
version: 1.0.0
dataset_uuid: 7d4a695f-2ab8-44e6-9b87-4dd909ab175d
