slice_name: SI2 - Largest Negative Movement by %
viz_type: big_number_total
params:
  adhoc_filters: []
  datasource: 68__table
  extra_form_data: {}
  header_font_size: 0.4
  metric: Largest Neg Movement %
  slice_id: 286
  subheader_font_size: 0.15
  time_format: '%d-%m-%Y %H:%M:%S'
  time_range: Last week
  url_params: {}
  viz_type: big_number_total
  y_axis_format: .2%
cache_timeout: null
uuid: 79fd3d5c-5b08-435a-874b-5ea78d123eec
version: 1.0.0
dataset_uuid: 7d4a695f-2ab8-44e6-9b87-4dd909ab175d
