slice_name: SI2 - Trades Today
description: null
certified_by: null
certification_details: null
viz_type: pie
params:
  adhoc_filters:
  - clause: WHERE
    comparator: N
    expressionType: SIMPLE
    filterOptionName: filter_3q9bn8vgyjt_4y4hq5rjzwo
    isExtra: false
    isNew: false
    operator: ==
    sqlExpression: null
    subject: Cancelled
  - clause: WHERE
    comparator: 'Yes'
    expressionType: SIMPLE
    filterOptionName: filter_qtwsb8jsw3q_lae1a8rixea
    isExtra: false
    isNew: false
    operator: ==
    operatorId: EQUALS
    sqlExpression: null
    subject: CURRENT DAY FLAG
  color_scheme: supersetColors
  datasource: 76__table
  date_format: smart_date
  donut: true
  extra_form_data: {}
  granularity_sqla: deal_date
  groupby:
  - Cash Gross Amount Group
  innerRadius: 50
  label_line: true
  label_type: key
  labels_outside: true
  legendOrientation: top
  legendType: scroll
  metric: count
  number_format: ~g
  outerRadius: 65
  row_limit: 100
  show_labels: true
  show_labels_threshold: 5
  show_legend: false
  slice_id: 314
  sort_by_metric: true
  time_range: No filter
  url_params: {}
  viz_type: pie
query_context: null
cache_timeout: null
uuid: 08e5056d-a1b3-4f74-a385-1fe8a582e3f0
version: 1.0.0
dataset_uuid: ebf32c00-65fc-4211-98df-7bbfec2a9c69
