slice_name: SI2 - Today's Positive Net Movements
description: Version 1.0 (21-07-2021) CDIG002 Confidential
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters:
  - clause: WHERE
    comparator: '0'
    expressionType: SIMPLE
    filterOptionName: filter_rgzjdk7zv6_w3sgopegrgi
    isExtra: false
    isNew: false
    operator: '>'
    sqlExpression: null
    subject: fund_movement_value
  all_columns:
  - share_class_name
  - fund_movement_percent
  color_pn: false
  column_config:
    fund_movement_percent:
      d3NumberFormat: .2%
      d3SmallNumberFormat: .2%
      showCellBars: false
  conditional_formatting: []
  datasource: 68__table
  extra_form_data: {}
  groupby: []
  include_search: true
  metrics:
  - count
  order_by_cols:
  - '["Today''s Movement %", false]'
  order_desc: true
  page_length: 10
  percent_metrics: []
  query_mode: raw
  row_limit: 10000
  server_page_length: 10
  show_cell_bars: false
  slice_id: 303
  table_timestamp_format: smart_date
  time_grain_sqla: P1D
  time_range: Last week
  url_params: {}
  viz_type: table
query_context: null
cache_timeout: null
uuid: 39d2df75-991a-4b01-ac3d-4c4fb69ba936
version: 1.0.0
dataset_uuid: 7d4a695f-2ab8-44e6-9b87-4dd909ab175d
