slice_name: SI2 - Trade Origins
description: null
certified_by: null
certification_details: null
viz_type: pie
params:
  adhoc_filters:
  - clause: WHERE
    comparator: N
    expressionType: SIMPLE
    filterOptionName: filter_ad50brpv0tj_u30forht87t
    isExtra: false
    isNew: false
    operator: ==
    sqlExpression: null
    subject: Cancelled
  - clause: WHERE
    comparator: 'Yes'
    expressionType: SIMPLE
    filterOptionName: filter_pp6z67n1xx_tgxdd3h9e8
    isExtra: false
    isNew: false
    operator: ==
    sqlExpression: null
    subject: CURRENT DAY FLAG
  color_scheme: supersetColors
  datasource: 76__table
  donut: true
  granularity_sqla: deal_date
  groupby:
  - trade_origin
  innerRadius: 49
  label_line: true
  label_type: key
  labels_outside: true
  legendOrientation: top
  legendType: scroll
  metric: count
  number_format: SMART_NUMBER
  outerRadius: 65
  row_limit: 100
  show_labels: true
  slice_id: 307
  time_range: No filter
  url_params: {}
  viz_type: pie
query_context: null
cache_timeout: null
uuid: 931e6262-af75-4526-96f4-603490bbfbc2
version: 1.0.0
dataset_uuid: ebf32c00-65fc-4211-98df-7bbfec2a9c69
