slice_name: SI2 - Largest Positive Movement by %
description: Version 1.0 (21-07-2021) CDIG002 Confidential
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  adhoc_filters: []
  datasource: 68__table
  extra_form_data: {}
  header_font_size: 0.4
  metric: Largest Pos Movement %
  slice_id: 287
  subheader_font_size: 0.15
  time_format: '%d-%m-%Y %H:%M:%S'
  time_range: Last week
  url_params: {}
  viz_type: big_number_total
  y_axis_format: .2%
query_context: null
cache_timeout: null
uuid: 8bf95195-b71b-4987-b139-a9ad0021c66b
version: 1.0.0
dataset_uuid: 7d4a695f-2ab8-44e6-9b87-4dd909ab175d
