slice_name: "SI4 - Today\u2019s Notifiable Deals"
description: Version 1.0 (21-04-2022) CDIG029 Confidential
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters:
  - clause: WHERE
    comparator: 'Yes'
    expressionType: SIMPLE
    filterOptionName: filter_m07p8jcdiws_427x8nrnftb
    isExtra: false
    isNew: false
    operator: ==
    operatorId: EQUALS
    sqlExpression: null
    subject: Current Day Flag (Deal Date)
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_jei4cy7lhmg_zwjc1lw5lg
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: transaction_type !~~ 'Transfer%' and transaction_type <> 'Reinvestment'
    subject: null
  - clause: WHERE
    comparator: N
    expressionType: SIMPLE
    filterOptionName: filter_7gxrdqa2rp3_zfahbrjv46o
    isExtra: false
    isNew: false
    operator: ==
    operatorId: EQUALS
    sqlExpression: null
    subject: cancelled
  - clause: WHERE
    comparator: Y
    expressionType: SIMPLE
    filterOptionName: filter_08tixchhipjb_bn68gsi6ofi
    isExtra: false
    isNew: false
    operator: ==
    operatorId: EQUALS
    sqlExpression: null
    subject: notifiable_deal_flag
  align_pn: false
  all_columns:
  - Fund Name
  - unitholder_id
  - deal_id
  - Deal Origin
  - transaction_type
  - price_type
  - bookvp_date
  - percent_of_fund
  - "Today\u2019s Unit Movement"
  - "Today\u2019s Cash Movement"
  color_pn: false
  column_config:
    "Today\u2019s Cash Movement":
      d3NumberFormat: ',.2f'
      d3SmallNumberFormat: ',.2f'
      showCellBars: false
    "Today\u2019s Unit Movement":
      d3NumberFormat: ',.4f'
      d3SmallNumberFormat: ',.4f'
      showCellBars: false
    bookvp_date:
      d3TimeFormat: '%d/%m/%Y'
    percent_of_fund:
      d3NumberFormat: .2%
      d3SmallNumberFormat: .2%
      showCellBars: false
  conditional_formatting: []
  datasource: 88__table
  extra_form_data: {}
  granularity_sqla: deal_date
  groupby: []
  include_search: true
  order_by_cols:
  - '["deal_id", false]'
  order_desc: true
  percent_metrics: []
  query_mode: raw
  row_limit: 10000
  server_page_length: 10
  show_cell_bars: false
  slice_id: 373
  table_timestamp_format: smart_date
  time_grain_sqla: P1D
  time_range: No filter
  url_params: {}
  viz_type: table
query_context: null
cache_timeout: null
uuid: 8d79fa7c-d182-42f0-86f3-dd7751f3f555
version: 1.0.0
dataset_uuid: 81bf2829-3db1-4e8d-a82f-c0aea2afff8a
