slice_name: SI4 - Largest Negative Movement by Value
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  adhoc_filters: []
  datasource: 87__table
  extra_form_data: {}
  granularity_sqla: null
  header_font_size: 0.4
  metric: Largest Negative Movement Value
  slice_id: 359
  subheader_font_size: 0.15
  time_format: '%d-%m-%Y %H:%M:%S'
  time_range: No filter
  url_params: {}
  viz_type: big_number_total
  y_axis_format: .3s
query_context: null
cache_timeout: null
uuid: 3d8b9077-17f2-4516-941f-b2740157cb09
version: 1.0.0
dataset_uuid: 22a4c3aa-d02c-4d98-9493-d90c79f5d3ac
