slice_name: SI4 - EIN Currency Filter
description: null
certified_by: null
certification_details: null
viz_type: filter_box
params:
  adhoc_filters: []
  datasource: 47__table
  date_filter: false
  extra_form_data: {}
  filter_configs:
  - asc: true
    clearable: true
    column: bpo_identifier
    key: 6Pu8JZlQZ
    label: BPO IDENTIFIER
    multiple: true
    searchAllOptions: false
  - asc: true
    clearable: true
    column: ein
    key: _Io8Pd3xT
    label: EIN
    multiple: true
    searchAllOptions: false
  - asc: true
    clearable: true
    column: emc_currency
    key: irQRYb5J-
    label: Currency
    multiple: true
    searchAllOptions: false
  granularity_sqla: null
  instant_filtering: true
  show_sqla_time_granularity: false
  slice_id: 363
  time_grain_sqla: P1D
  time_range: No filter
  url_params: {}
  viz_type: filter_box
query_context: null
cache_timeout: null
uuid: 9c8337c3-8ae7-4519-9c5c-e6d7dc3cc2de
version: 1.0.0
dataset_uuid: 9a8d10d9-ddab-ce94-c003-5f6f275d928f
