slice_name: SI4 - Transactions By Country
description: null
certified_by: null
certification_details: null
viz_type: pie
params:
  adhoc_filters:
  - clause: WHERE
    comparator: N
    expressionType: SIMPLE
    filterOptionName: filter_mxvke3dt0qi_orle0kxhpl
    isExtra: false
    isNew: false
    operator: ==
    operatorId: EQUALS
    sqlExpression: null
    subject: cancelled
  color_scheme: supersetColors
  datasource: 93__table
  date_format: smart_date
  donut: true
  extra_form_data: {}
  granularity_sqla: eff_date
  groupby:
  - country
  innerRadius: 50
  label_line: false
  label_type: key
  labels_outside: false
  legendOrientation: right
  legendType: plain
  metric:
    aggregate: COUNT_DISTINCT
    column:
      certification_details: null
      certified_by: null
      column_name: deal_id
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 3124
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: VARCHAR(20)
      type_generic: 1
      verbose_name: null
      warning_markdown: null
    expressionType: SIMPLE
    hasCustomLabel: false
    isNew: false
    label: COUNT_DISTINCT(deal_id)
    optionName: metric_9zheb6t4h2m_2rnoacd7xv6
    sqlExpression: null
  number_format: SMART_NUMBER
  outerRadius: 65
  row_limit: 100
  show_labels: false
  show_labels_threshold: 5
  show_legend: true
  slice_id: 425
  sort_by_metric: true
  time_range: 'DATEADD(DATETIME("now"), -2, month) : now'
  url_params: {}
  viz_type: pie
query_context: null
cache_timeout: null
uuid: 56599a86-c55a-449f-b3e7-dbead332d032
version: 1.0.0
dataset_uuid: 74fa6896-5e25-4630-b057-9f43589743fa
