slice_name: SI4 - Investor Category Today's Deals
description: null
certified_by: null
certification_details: null
viz_type: pie
params:
  adhoc_filters:
  - clause: WHERE
    comparator: 'Yes'
    expressionType: SIMPLE
    filterOptionName: filter_7emall85pke_lzchy6ujfhm
    isExtra: false
    isNew: false
    operator: ==
    operatorId: EQUALS
    sqlExpression: null
    subject: Current Day Flag (Deal Date)
  - clause: WHERE
    comparator: N
    expressionType: SIMPLE
    filterOptionName: filter_29dnajqyxqb_lp4i0qkwy6p
    isExtra: false
    isNew: false
    operator: ==
    operatorId: EQUALS
    sqlExpression: null
    subject: cancelled
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_97cd1hye2fs_gwtcsh48y3
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: transaction_type !~~ 'Transfer%' and transaction_type <> 'Reinvestment'
    subject: null
  color_scheme: supersetColors
  datasource: 88__table
  date_format: smart_date
  donut: true
  extra_form_data: {}
  granularity_sqla: deal_date
  groupby:
  - investor_type
  innerRadius: 50
  label_line: true
  label_type: key
  labels_outside: true
  legendOrientation: top
  legendType: scroll
  metric:
    aggregate: COUNT_DISTINCT
    column:
      certification_details: null
      certified_by: null
      column_name: deal_id
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 2811
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: VARCHAR(30)
      type_generic: 1
      verbose_name: Deal ID
      warning_markdown: null
    expressionType: SIMPLE
    hasCustomLabel: false
    isNew: false
    label: COUNT_DISTINCT(Deal ID)
    optionName: metric_602duxwbqvq_7vgplrg6h97
    sqlExpression: null
  number_format: SMART_NUMBER
  outerRadius: 65
  row_limit: 100
  show_labels: true
  show_labels_threshold: 5
  show_legend: false
  slice_id: 385
  sort_by_metric: true
  time_range: No filter
  url_params: {}
  viz_type: pie
query_context: null
cache_timeout: null
uuid: 006a91f2-f341-4b45-9271-fd4324a8bd91
version: 1.0.0
dataset_uuid: 81bf2829-3db1-4e8d-a82f-c0aea2afff8a
