slice_name: SI4 - Assets Under Management
viz_type: big_number_total
params:
  adhoc_filters: []
  datasource: 87__table
  extra_form_data: {}
  header_font_size: 0.4
  metric: Last Fund Value
  subheader_font_size: 0.15
  time_format: '%d-%m-%Y %H:%M:%S'
  time_range: No filter
  url_params: {}
  viz_type: big_number_total
  y_axis_format: SMART_NUMBER
cache_timeout: null
uuid: 0da4a3d4-1b97-4beb-ab7f-fc3d85eec230
version: 1.0.0
dataset_uuid: 22a4c3aa-d02c-4d98-9493-d90c79f5d3ac
