slice_name: SI4 - Clients With a Failed AML Status
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters:
  - clause: WHERE
    comparator: Inactive
    expressionType: SIMPLE
    filterOptionName: filter_5ewjfkfqda6_9sa4zpqz5s
    isExtra: false
    isNew: false
    operator: ==
    operatorId: EQUALS
    sqlExpression: null
    subject: anti_money_laundering_status
  - clause: WHERE
    comparator: N
    expressionType: SIMPLE
    filterOptionName: filter_ts9m36pieo_311uwv1m9eu
    isExtra: false
    isNew: false
    operator: ==
    operatorId: EQUALS
    sqlExpression: null
    subject: cancelled
  all_columns: []
  color_pn: false
  conditional_formatting: []
  datasource: 93__table
  extra_form_data: {}
  granularity_sqla: eff_date
  groupby:
  - anti_money_laundering_status
  - unitholder_id
  - client_name
  - client_category
  - client_type
  order_by_cols: []
  order_desc: false
  page_length: 10
  percent_metrics: []
  query_mode: aggregate
  row_limit: 10000
  server_page_length: 10
  show_cell_bars: false
  slice_id: 429
  table_timestamp_format: smart_date
  time_grain_sqla: P1D
  time_range: 'DATEADD(DATETIME("now"), -2, month) : now'
  timeseries_limit_metric:
    aggregate: null
    column: null
    expressionType: SQL
    hasCustomLabel: false
    isNew: false
    label: anti_money_laundering_status asc,unithol...
    optionName: metric_jn28hebnmub_6o3aitwut5o
    sqlExpression: anti_money_laundering_status asc,unitholder_id
  url_params: {}
  viz_type: table
query_context: null
cache_timeout: null
uuid: 34116ead-5da6-4431-a4fd-4aa3a8c2c1d0
version: 1.0.0
dataset_uuid: 74fa6896-5e25-4630-b057-9f43589743fa
