slice_name: SI4 - Today's Negative Movements
description: Version 1.0 (21-04-2022) CDIG029 Confidential
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters:
  - clause: WHERE
    comparator: '0'
    expressionType: SIMPLE
    filterOptionName: filter_hmxyfdshh5h_nmtuvw9b4eq
    isExtra: false
    isNew: false
    operator: <
    operatorId: LESS_THAN
    sqlExpression: null
    subject: fund_movement_value
  all_columns:
  - fund_code
  - fund_name
  - Price Status
  - last_price_amount
  - "Today\u2019s Cash Movement"
  - "Today\u2019s % Movement"
  color_pn: false
  column_config:
    "Today\u2019s % Movement":
      d3NumberFormat: .2%
      d3SmallNumberFormat: .2%
    "Today\u2019s Cash Movement":
      d3NumberFormat: ',.2f'
      d3SmallNumberFormat: ',.2f'
    last_price_amount:
      d3NumberFormat: ',.4f'
      d3SmallNumberFormat: ',.4f'
  conditional_formatting: []
  datasource: 87__table
  extra_form_data: {}
  granularity_sqla: null
  groupby: []
  order_by_cols:
  - '["Negative Net Movements", true]'
  order_desc: true
  page_length: 20
  percent_metrics: []
  query_mode: raw
  row_limit: 10000
  server_page_length: 10
  show_cell_bars: false
  slice_id: 368
  table_timestamp_format: smart_date
  time_grain_sqla: P1D
  time_range: No filter
  url_params: {}
  viz_type: table
query_context: null
cache_timeout: null
uuid: 4ae24f67-cdec-4e5c-abcd-1b9a41b34c18
version: 1.0.0
dataset_uuid: 22a4c3aa-d02c-4d98-9493-d90c79f5d3ac
