slice_name: "SI4 - Today\u2019s Notifiable Deals by Origin"
description: null
certified_by: null
certification_details: null
viz_type: dist_bar
params:
  adhoc_filters:
  - clause: WHERE
    comparator: 'Yes'
    expressionType: SIMPLE
    filterOptionName: filter_itfpc6i1iqd_kljy66fo66
    isExtra: false
    isNew: false
    operator: ==
    operatorId: EQUALS
    sqlExpression: null
    subject: Current Day Flag (Deal Date)
  - clause: WHERE
    comparator: N
    expressionType: SIMPLE
    filterOptionName: filter_7hlc6bpbsr_qkcabp46fso
    isExtra: false
    isNew: false
    operator: ==
    operatorId: EQUALS
    sqlExpression: null
    subject: cancelled
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_3pnr5psrvwj_vcjo8ekpp0o
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: transaction_type !~~ 'Transfer%' and transaction_type <> 'Reinvestment'
    subject: null
  - clause: WHERE
    comparator: Y
    expressionType: SIMPLE
    filterOptionName: filter_5u802e4n9qu_mvc8kxbmqa
    isExtra: false
    isNew: false
    operator: ==
    operatorId: EQUALS
    sqlExpression: null
    subject: notifiable_deal_flag
  bar_stacked: true
  bottom_margin: auto
  color_scheme: supersetColors
  columns:
  - Fund Name
  datasource: 88__table
  extra_form_data: {}
  granularity_sqla: deal_date
  groupby:
  - trade_origin
  metrics:
  - aggregate: COUNT_DISTINCT
    column:
      certification_details: null
      certified_by: null
      column_name: deal_id
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 2811
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: VARCHAR(30)
      type_generic: 1
      verbose_name: Deal ID
      warning_markdown: null
    expressionType: SIMPLE
    hasCustomLabel: false
    isNew: false
    label: COUNT_DISTINCT(Deal ID)
    optionName: metric_8iktl54hv92_md1u3h6psgg
    sqlExpression: null
  order_desc: true
  row_limit: 10000
  show_legend: false
  slice_id: 372
  time_range: No filter
  url_params: {}
  viz_type: dist_bar
  x_ticks_layout: auto
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
query_context: null
cache_timeout: null
uuid: 4a13c806-cb2e-4ff0-a28a-c7e2964de8d3
version: 1.0.0
dataset_uuid: 81bf2829-3db1-4e8d-a82f-c0aea2afff8a
