slice_name: "SI4 - Today\u2019s Net Movement"
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  adhoc_filters: []
  datasource: 87__table
  extra_form_data: {}
  header_font_size: 0.4
  metric: Movement Value Total
  subheader_font_size: 0.15
  time_format: '%d-%m-%Y %H:%M:%S'
  time_range: No filter
  url_params: {}
  viz_type: big_number_total
  y_axis_format: SMART_NUMBER
query_context: null
cache_timeout: null
uuid: ce2dd3d8-3833-460f-a61d-c7261183cfed
version: 1.0.0
dataset_uuid: 22a4c3aa-d02c-4d98-9493-d90c79f5d3ac
