slice_name: SI4 - STP Detail
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters:
  - clause: WHERE
    comparator: 'Yes'
    expressionType: SIMPLE
    filterOptionName: filter_ge2s4zd8huh_4uujchvph5m
    isExtra: false
    isNew: false
    operator: ==
    operatorId: EQUALS
    sqlExpression: null
    subject: Current Day Flag (Deal Date)
  - clause: WHERE
    comparator: CTN
    expressionType: SIMPLE
    filterOptionName: filter_fm1owejihf_gzjb4picwh5
    isExtra: false
    isNew: false
    operator: ==
    operatorId: EQUALS
    sqlExpression: null
    subject: Deal Origin for STP
  - clause: WHERE
    comparator: N
    expressionType: SIMPLE
    filterOptionName: filter_q4n2bhkcseo_t1hetmv5s
    isExtra: false
    isNew: false
    operator: ==
    operatorId: EQUALS
    sqlExpression: null
    subject: cancelled
  all_columns:
  - Fund Name
  - unitholder_id
  - deal_id
  - trade_origin
  - transaction_type
  - price_type
  - Time of Trade VP
  - "Today\u2019s Unit Movement"
  - "Today\u2019s Cash Movement"
  color_pn: false
  column_config:
    "Today\u2019s Cash Movement":
      d3NumberFormat: ',.2f'
      d3SmallNumberFormat: ',.2f'
    "Today\u2019s Unit Movement":
      d3NumberFormat: ',.4f'
      d3SmallNumberFormat: ',.4f'
      showCellBars: false
    bookvp_date:
      d3TimeFormat: '%d/%m/%Y'
  conditional_formatting: []
  datasource: 88__table
  extra_form_data: {}
  granularity_sqla: deal_date
  groupby: []
  order_by_cols:
  - '["deal_id", false]'
  order_desc: true
  page_length: 10
  percent_metrics: []
  query_mode: raw
  row_limit: 10000
  server_page_length: 10
  show_cell_bars: false
  slice_id: 417
  table_timestamp_format: smart_date
  time_grain_sqla: P1D
  time_range: No filter
  url_params: {}
  viz_type: table
query_context: null
cache_timeout: null
uuid: b5a2608b-d10c-4060-91ff-5a491312e5c7
version: 1.0.0
dataset_uuid: 81bf2829-3db1-4e8d-a82f-c0aea2afff8a
