slice_name: SI5- Outstanding Breach Details(BRM)
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters:
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_gblhb9o69c7_if17ff76w0l
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: upper(breach_status) NOT IN ('VOID', 'CLOSED')
    subject: null
  all_columns:
  - days_since_identified_txt
  - breach_ref
  - unitholder_id
  - original_event_id
  - date_identified
  - part_outstanding
  - control_refs
  color_pn: false
  column_config:
    date_identified:
      d3TimeFormat: '%Y-%m-%d'
  conditional_formatting: []
  datasource: 97__table
  extra_form_data: {}
  granularity_sqla: update_datetime
  groupby: []
  include_search: true
  order_by_cols:
  - '["date_identified", true]'
  order_desc: true
  page_length: 20
  percent_metrics: []
  query_mode: raw
  row_limit: 10000
  server_page_length: 10
  show_cell_bars: false
  slice_id: 2000000019
  table_timestamp_format: smart_date
  time_grain_sqla: P1D
  time_range: No filter
  url_params: {}
  viz_type: table
query_context: '{"datasource": {"id": 97, "type": "table"}, "force": false, "queries":
  [{"time_range": "No filter", "granularity": "update_datetime", "filters": [], "extras":
  {"time_grain_sqla": "P1D", "having": "", "having_druid": [], "where": "(upper(breach_status)
  NOT IN (''VOID'', ''CLOSED''))"}, "applied_time_extras": {}, "columns": ["days_since_identified_txt",
  "breach_ref", "unitholder_id", "original_event_id", "date_identified", "part_outstanding",
  "control_refs"], "orderby": [["date_identified", true]], "annotation_layers": [],
  "row_limit": 10000, "timeseries_limit": 0, "order_desc": true, "url_params": {},
  "custom_params": {}, "custom_form_data": {}, "post_processing": []}], "result_format":
  "json", "result_type": "full"}'
cache_timeout: null
uuid: 7aad15c7-d73a-451a-a64b-be6677054513
version: 1.0.0
dataset_uuid: 9f0a237b-3856-4149-9f7b-70e2e9a25367
