slice_name: SI5 - Outstanding Complaints
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  adhoc_filters:
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_s94sxdet6i_omou8zk9f7
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: UPPER(complaint_status) NOT IN ('VOID')
    subject: null
  - clause: WHERE
    comparator: null
    expressionType: SIMPLE
    filterOptionName: filter_la7z2e5jupk_fkgqdowrblf
    isExtra: false
    isNew: false
    operator: IS NULL
    operatorId: IS_NULL
    sqlExpression: null
    subject: resolute_letter_date
  - clause: WHERE
    comparator: null
    expressionType: SIMPLE
    filterOptionName: filter_gm97ybfnn5w_stbdi1tw62r
    isExtra: false
    isNew: false
    operator: IS NOT NULL
    operatorId: IS_NOT_NULL
    sqlExpression: null
    subject: days_since_received_txt
  datasource: 98__table
  extra_form_data: {}
  granularity_sqla: received_date
  header_font_size: 0.4
  metric: total_outstanding
  slice_id: 551
  subheader_font_size: 0.15
  time_format: '%d-%m-%Y %H:%M:%S'
  time_range: No filter
  url_params: {}
  viz_type: big_number_total
  y_axis_format: ',d'
query_context: null
cache_timeout: null
uuid: 4dbc3753-7844-4e3f-b389-19becb17b42c
version: 1.0.0
dataset_uuid: bdc5b0a1-522c-4e73-9560-249150a7e262
