slice_name: SI5 - Part 2(s) to be Closed
viz_type: big_number_total
params:
  adhoc_filters:
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_ozwrjvavesa_3764tyuytxk
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: upper(part_outstanding) = 'PART 2'
    subject: null
  datasource: 97__table
  extra_form_data: {}
  granularity_sqla: update_datetime
  header_font_size: 0.4
  metric: total_part_2
  slice_id: 521
  subheader: ''
  subheader_font_size: 0.15
  time_format: '%d-%m-%Y %H:%M:%S'
  time_range: No filter
  url_params: {}
  viz_type: big_number_total
  y_axis_format: ',d'
cache_timeout: null
uuid: 09d263d9-ccfb-42f3-a448-6e7e78b6002a
version: 1.0.0
dataset_uuid: 9f0a237b-3856-4149-9f7b-70e2e9a25367
