slice_name: SI5 - Complaints Last 4 Weeks
description: null
certified_by: null
certification_details: null
viz_type: pie
params:
  adhoc_filters:
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_va7eq3ukj5_u088jjvmqb
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: complaint_status NOT IN ('Void')
    subject: null
  color_scheme: supersetColors
  datasource: 98__table
  date_format: smart_date
  donut: true
  extra_form_data: {}
  granularity_sqla: received_date
  groupby:
  - resolved_status
  innerRadius: 50
  label_line: true
  label_type: key
  labels_outside: true
  legendOrientation: top
  legendType: scroll
  metric: count
  number_format: ',d'
  outerRadius: 65
  row_limit: 100
  show_labels: true
  show_labels_threshold: 5
  show_legend: false
  slice_id: 534
  sort_by_metric: true
  time_range: 'DATEADD(DATETIME("today"), -4, week) : today'
  url_params: {}
  viz_type: pie
query_context: '{"datasource": {"id": 98, "type": "table"}, "force": false, "queries":
  [{"time_range": "DATEADD(DATETIME(\"today\"), -4, week) : today", "granularity":
  "received_date", "filters": [], "extras": {"having": "", "having_druid": [], "where":
  "(complaint_status NOT IN (''Void''))"}, "applied_time_extras": {}, "columns": ["resolved_status"],
  "metrics": ["count"], "orderby": [["count", false]], "annotation_layers": [], "row_limit":
  100, "timeseries_limit": 0, "order_desc": true, "url_params": {}, "custom_params":
  {}, "custom_form_data": {}}], "result_format": "json", "result_type": "full"}'
cache_timeout: null
uuid: 0e834171-eb23-4dbb-a08f-5a73c24752fd
version: 1.0.0
dataset_uuid: bdc5b0a1-522c-4e73-9560-249150a7e262
