slice_name: SI5 - Outstanding Complaints Services Insight
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  adhoc_filters: []
  datasource: 98__table
  extra_form_data: {}
  granularity_sqla: received_date
  header_font_size: 0.4
  metric: total_outstanding
  slice_id: 535
  subheader_font_size: 0.15
  time_format: '%d-%m-%Y %H:%M:%S'
  time_range: No filter
  url_params: {}
  viz_type: big_number_total
  y_axis_format: ',d'
query_context: null
cache_timeout: null
uuid: 6404a683-d1c4-478e-a067-5545fb769fa3
version: 1.0.0
dataset_uuid: bdc5b0a1-522c-4e73-9560-249150a7e262
