slice_name: SI5 - Significant Breaches - Last 4 Weeks
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  adhoc_filters:
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_mlzd86u60nq_6yjgo31qcjo
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: UPPER(significance_flag) = 'YES'
    subject: null
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_v8u7lfm62w8_n9gqn4bt5i
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: original_closed_date >= date_trunc('Week',(current_date - INTERVAL
      '3 weeks'))::date
    subject: null
  datasource: 97__table
  extra_form_data: {}
  granularity_sqla: original_closed_date
  header_font_size: 0.4
  metric: total
  slice_id: 539
  subheader_font_size: 0.15
  time_format: '%d-%m-%Y %H:%M:%S'
  time_range: No filter
  url_params: {}
  viz_type: big_number_total
  y_axis_format: ',d'
query_context: null
cache_timeout: null
uuid: 1a99791a-6aec-4dd5-ab24-ca69268f380b
version: 1.0.0
dataset_uuid: 9f0a237b-3856-4149-9f7b-70e2e9a25367
