slice_name: SI5 - Active Work by Work Type - Top 10
description: null
certified_by: null
certification_details: null
viz_type: dist_bar
params:
  adhoc_filters:
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_fhfws3upjyl_694qszgy0lb
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: UPPER(queuecd) <> 'END'
    subject: null
  bottom_margin: auto
  color_scheme: supersetColors
  columns: []
  datasource: 96__table
  extra_form_data: {}
  granularity_sqla: last_update_dattim
  groupby:
  - wrktype
  metrics:
  - count
  order_desc: true
  row_limit: 10
  show_legend: false
  slice_id: 548
  time_range: No filter
  url_params: {}
  viz_type: dist_bar
  x_ticks_layout: auto
  y_axis_bounds:
  - null
  - null
  y_axis_format: ',d'
  y_axis_label: Number of Work Items
  y_axis_showminmax: false
query_context: null
cache_timeout: null
uuid: cc789d10-1b1c-4f4f-a438-f59747cd28d2
version: 1.0.0
dataset_uuid: 2c52393b-92f3-4a51-9ff7-3d0349ae0245
