slice_name: SI5 - Active Work Team Filter
description: null
certified_by: null
certification_details: null
viz_type: filter_box
params:
  adhoc_filters:
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_frlygz40mzr_rdf6nepy3pk
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: UPPER(processing_stage) <> 'END'
    subject: null
  datasource: 96__table
  date_filter: false
  extra_form_data: {}
  filter_configs:
  - asc: true
    clearable: true
    column: owner_team
    key: tslhlKa4W
    label: TEAM
    multiple: true
    searchAllOptions: false
  granularity_sqla: last_update_dattim
  instant_filtering: true
  slice_id: 541
  time_grain_sqla: P1D
  time_range: No filter
  url_params: {}
  viz_type: filter_box
query_context: '{"datasource": {"id": 96, "type": "table"}, "force": false, "queries":
  [{"time_range": "No filter", "granularity": "last_update_dattim", "filters": [],
  "extras": {"time_grain_sqla": "P1D", "having": "", "having_druid": [], "where":
  "(UPPER(processing_stage) <> ''END'')"}, "applied_time_extras": {}, "columns": [],
  "metrics": [], "annotation_layers": [], "timeseries_limit": 0, "order_desc": true,
  "url_params": {}, "custom_params": {}, "custom_form_data": {}}], "result_format":
  "json", "result_type": "full"}'
cache_timeout: null
uuid: b60a77a2-445c-4728-b5c6-7ae90db25d0e
version: 1.0.0
dataset_uuid: 2c52393b-92f3-4a51-9ff7-3d0349ae0245
