slice_name: SI5 - Active Work Processing Stage Filter
description: null
certified_by: null
certification_details: null
viz_type: filter_box
params:
  adhoc_filters:
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_n398gp7fn0d_ti9ls7fcynn
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: UPPER(processing_stage) <> 'END'
    subject: null
  datasource: 96__table
  date_filter: false
  extra_form_data: {}
  filter_configs:
  - asc: true
    clearable: true
    column: processing_stage
    key: McTOZ7a1h
    label: PROCESSING STAGE
    metric: processing_stage_filter
    multiple: true
    searchAllOptions: false
  granularity_sqla: last_update_dattim
  instant_filtering: true
  slice_id: 543
  time_grain_sqla: P1D
  time_range: No filter
  url_params: {}
  viz_type: filter_box
query_context: '{"datasource": {"id": 96, "type": "table"}, "force": false, "queries":
  [{"time_range": "No filter", "granularity": "last_update_dattim", "filters": [],
  "extras": {"time_grain_sqla": "P1D", "having": "", "having_druid": [], "where":
  "(UPPER(processing_stage) <> ''END'')"}, "applied_time_extras": {}, "columns": [],
  "metrics": [], "annotation_layers": [], "timeseries_limit": 0, "order_desc": true,
  "url_params": {}, "custom_params": {}, "custom_form_data": {}}], "result_format":
  "json", "result_type": "full"}'
cache_timeout: null
uuid: b8badfc0-d118-4726-8924-264b43339831
version: 1.0.0
dataset_uuid: 2c52393b-92f3-4a51-9ff7-3d0349ae0245
