slice_name: SI5 - Outstanding Breaches by Age
description: null
certified_by: null
certification_details: null
viz_type: dist_bar
params:
  adhoc_filters:
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_ni6wqe9bmea_xp2qfktasr
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: upper(breach_status) NOT IN ('VOID', 'CLOSED')
    subject: null
  bottom_margin: auto
  color_scheme: supersetColors
  columns: []
  datasource: 97__table
  extra_form_data: {}
  granularity_sqla: original_closed_date
  groupby:
  - age_in_working_days
  metrics:
  - total_outstanding
  order_bars: true
  order_desc: false
  row_limit: 10000
  show_bar_value: false
  show_controls: false
  show_legend: false
  slice_id: 522
  time_range: No filter
  url_params: {}
  viz_type: dist_bar
  x_axis_label: Age in Working Days
  x_ticks_layout: flat
  y_axis_bounds:
  - null
  - null
  y_axis_format: ',d'
  y_axis_label: Number of Breaches
  y_axis_showminmax: false
query_context: '{"datasource": {"id": 97, "type": "table"}, "force": false, "queries":
  [{"time_range": "No filter", "granularity": "original_closed_date", "filters": [],
  "extras": {"having": "", "having_druid": [], "where": "(upper(breach_status) NOT
  IN (''VOID'', ''CLOSED''))"}, "applied_time_extras": {}, "columns": ["age_in_working_days"],
  "metrics": ["total_outstanding"], "annotation_layers": [], "row_limit": 10000, "timeseries_limit":
  0, "order_desc": false, "url_params": {}, "custom_params": {}, "custom_form_data":
  {}}], "result_format": "json", "result_type": "full"}'
cache_timeout: null
uuid: 6e5e627a-dc90-4cda-8e24-7f1488c3234d
version: 1.0.0
dataset_uuid: 9f0a237b-3856-4149-9f7b-70e2e9a25367
