slice_name: SI5 - Notified in the Last 4 Weeks
description: null
certified_by: null
certification_details: null
viz_type: pie
params:
  adhoc_filters:
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_z02b75omx58_gwdljwcvdwj
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: upper(breach_status) NOT IN ('VOID')
    subject: null
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_yxm57c9tus_h1wsz5epwgp
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: original_closed_date >= date_trunc('Week',(current_date - INTERVAL
      '3 weeks'))::date
    subject: null
  color_scheme: supersetColors
  datasource: 97__table
  date_format: smart_date
  donut: true
  extra_form_data: {}
  granularity_sqla: original_closed_date
  groupby:
  - breach_type
  innerRadius: 50
  label_line: true
  label_type: key
  labels_outside: true
  legendOrientation: bottom
  legendType: scroll
  metric: count
  number_format: ',d'
  outerRadius: 65
  row_limit: 100
  show_labels: true
  show_labels_threshold: 5
  show_legend: false
  slice_id: 523
  sort_by_metric: true
  time_range: No filter
  url_params: {}
  viz_type: pie
query_context: '{"datasource": {"id": 97, "type": "table"}, "force": false, "queries":
  [{"time_range": "No filter", "granularity": "original_closed_date", "filters": [],
  "extras": {"having": "", "having_druid": [], "where": "(upper(breach_status) NOT
  IN (''VOID'')) AND (original_closed_date >= date_trunc(''Week'',(current_date -
  INTERVAL ''3 weeks''))::date)"}, "applied_time_extras": {}, "columns": ["breach_type"],
  "metrics": ["count"], "orderby": [["count", false]], "annotation_layers": [], "row_limit":
  100, "timeseries_limit": 0, "order_desc": true, "url_params": {}, "custom_params":
  {}, "custom_form_data": {}}], "result_format": "json", "result_type": "full"}'
cache_timeout: null
uuid: e63e4fa4-389f-456a-8bde-a889246f7578
version: 1.0.0
dataset_uuid: 9f0a237b-3856-4149-9f7b-70e2e9a25367
