slice_name: SI5 - Total Breaches - Last 4 Weeks
viz_type: big_number_total
params:
  adhoc_filters:
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_6r19xwxyegx_u5ours0g93r
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: original_closed_date >= date_trunc('Week',(current_date - INTERVAL
      '3 weeks'))::date
    subject: null
  datasource: 97__table
  extra_form_data: {}
  granularity_sqla: original_closed_date
  header_font_size: 0.4
  metric: total
  slice_id: 525
  subheader_font_size: 0.15
  time_format: '%d-%m-%Y %H:%M:%S'
  time_range: No filter
  url_params: {}
  viz_type: big_number_total
  y_axis_format: ',d'
cache_timeout: null
uuid: 68429690-5d8e-4d24-867a-127937316c4a
version: 1.0.0
dataset_uuid: 9f0a237b-3856-4149-9f7b-70e2e9a25367
