slice_name: SI5 - EIN Currency Filter
description: null
certified_by: null
certification_details: null
viz_type: filter_box
params:
  adhoc_filters: []
  datasource: 47__table
  date_filter: false
  extra_form_data: {}
  filter_configs:
  - asc: true
    clearable: true
    column: bpo_identifier
    key: iarv-gUkp
    label: BPO Identifier
    multiple: true
    searchAllOptions: false
  - asc: true
    clearable: true
    column: ein
    key: PsLjdu27S
    label: EIN
    multiple: true
    searchAllOptions: false
  - asc: true
    clearable: true
    column: emc_currency
    key: BAbNGVlXZ
    label: Currency
    multiple: true
    searchAllOptions: false
  instant_filtering: true
  slice_id: 516
  time_grain_sqla: P1D
  time_range: No filter
  url_params: {}
  viz_type: filter_box
query_context: '{"datasource": {"id": 47, "type": "table"}, "force": false, "queries":
  [{"time_range": "No filter", "filters": [], "extras": {"time_grain_sqla": "P1D",
  "having": "", "having_druid": [], "where": ""}, "applied_time_extras": {}, "columns":
  [], "metrics": [], "annotation_layers": [], "timeseries_limit": 0, "order_desc":
  true, "url_params": {}, "custom_params": {}, "custom_form_data": {}}], "result_format":
  "json", "result_type": "full"}'
cache_timeout: null
uuid: 8095ee41-3243-44be-9dda-ae55c4d59a5c
version: 1.0.0
dataset_uuid: 9a8d10d9-ddab-ce94-c003-5f6f275d928f
