slice_name: SI5 - Complaints Received - Last 2 Weeks
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  adhoc_filters: []
  datasource: 98__table
  extra_form_data: {}
  granularity_sqla: received_date
  header_font_size: 0.4
  metric: total_received
  slice_id: 552
  subheader: ''
  subheader_font_size: 0.15
  time_format: '%d-%m-%Y %H:%M:%S'
  time_range: 'DATEADD(DATETIME("today"), -2, week) : today'
  url_params: {}
  viz_type: big_number_total
  y_axis_format: ',d'
query_context: '{"datasource": {"id": 98, "type": "table"}, "force": false, "queries":
  [{"time_range": "DATEADD(DATETIME(\"today\"), -2, week) : today", "granularity":
  "received_date", "filters": [], "extras": {"having": "", "having_druid": [], "where":
  ""}, "applied_time_extras": {}, "columns": [], "metrics": ["total_received"], "annotation_layers":
  [], "timeseries_limit": 0, "order_desc": true, "url_params": {}, "custom_params":
  {}, "custom_form_data": {}}], "result_format": "json", "result_type": "full"}'
cache_timeout: null
uuid: 77cd1b95-884f-4152-b053-cbad574923d7
version: 1.0.0
dataset_uuid: bdc5b0a1-522c-4e73-9560-249150a7e262
