slice_name: SI5 - Referred Work Items
viz_type: big_number_total
params:
  adhoc_filters:
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_e0u50eg0pl9_iz9di8ri01a
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: upper(statcd) = 'REFREG'
    subject: null
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_hu837h1202g_fiuaum7cpg8
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: upper(queuecd) <> 'END'
    subject: null
  datasource: 96__table
  extra_form_data: {}
  granularity_sqla: last_update_dattim
  header_font_size: 0.4
  metric: count
  slice_id: 530
  subheader_font_size: 0.15
  time_format: '%d-%m-%Y %H:%M:%S'
  time_range: No filter
  url_params: {}
  viz_type: big_number_total
  y_axis_format: ',d'
cache_timeout: null
uuid: dfc1756e-acfa-444f-ac68-f2bacc1e33b5
version: 1.0.0
dataset_uuid: 2c52393b-92f3-4a51-9ff7-3d0349ae0245
