slice_name: SI6 - Oldest Work Items by Work Type
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters: []
  all_columns: []
  color_pn: true
  column_config:
    Number of Business Days Since Received:
      d3NumberFormat: ',d'
      d3SmallNumberFormat: ',d'
      showCellBars: false
  conditional_formatting: []
  datasource: 2000000005__table
  extra_form_data: {}
  granularity_sqla: last_update_dattim
  groupby:
  - wrktype
  metrics:
  - aggregate: MAX
    column:
      certification_details: null
      certified_by: null
      column_name: age_bus_days
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 2000000090
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: INTEGER
      type_generic: 0
      verbose_name: Age in Business Days
      warning_markdown: null
    expressionType: SIMPLE
    hasCustomLabel: true
    isNew: false
    label: Number of Business Days Since Received
    optionName: metric_08qhexoar1uo_jfrlk0qfkfh
    sqlExpression: null
  order_by_cols: []
  order_desc: true
  page_length: 20
  percent_metrics: []
  query_mode: aggregate
  row_limit: 10000
  server_page_length: 10
  show_cell_bars: false
  slice_id: 2000000030
  table_timestamp_format: smart_date
  time_grain_sqla: P1D
  time_range: No filter
  timeseries_limit_metric:
    aggregate: MAX
    column:
      certification_details: null
      certified_by: null
      column_name: age_bus_days
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 2000000090
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: INTEGER
      type_generic: 0
      verbose_name: Age in Business Days
      warning_markdown: null
    expressionType: SIMPLE
    hasCustomLabel: true
    isNew: false
    label: Number of Business Days Since Received
    optionName: metric_ylckl3porjg_v159na2kv4d
    sqlExpression: null
  url_params: {}
  viz_type: table
query_context: null
cache_timeout: null
uuid: b4f736c7-ca37-439b-8ada-149997818dff
version: 1.0.0
dataset_uuid: deb426d2-5ea7-42ae-ae97-c99694c2ddff
