slice_name: SI6 - Active Work Team Filter
description: null
certified_by: null
certification_details: null
viz_type: filter_box
params:
  adhoc_filters: []
  datasource: 2000000005__table
  date_filter: false
  extra_form_data: {}
  filter_configs:
  - asc: true
    clearable: true
    column: owner_team
    key: lRp87pwJJ
    label: TEAM
    multiple: true
    searchAllOptions: false
  granularity_sqla: last_update_dattim
  instant_filtering: true
  slice_id: 2000000036
  time_grain_sqla: P1D
  time_range: No filter
  url_params: {}
  viz_type: filter_box
query_context: null
cache_timeout: null
uuid: e4fc553d-5c70-4c25-8abd-a48c4711c90d
version: 1.0.0
dataset_uuid: deb426d2-5ea7-42ae-ae97-c99694c2ddff
