slice_name: "SI6 - Active Work by Work Type \u2013 Top 10"
description: null
certified_by: null
certification_details: null
viz_type: dist_bar
params:
  adhoc_filters: []
  bottom_margin: auto
  color_scheme: supersetColors
  columns: []
  datasource: 2000000005__table
  extra_form_data: {}
  granularity_sqla: last_update_dattim
  groupby:
  - wrktype
  metrics:
  - count
  order_desc: true
  row_limit: 10
  show_legend: true
  slice_id: 2000000029
  time_range: No filter
  url_params: {}
  viz_type: dist_bar
  x_ticks_layout: auto
  y_axis_bounds:
  - null
  - null
  y_axis_format: ',d'
  y_axis_label: Number of Work Items
query_context: null
cache_timeout: null
uuid: 65bd6fc4-7425-42c8-9fc7-58ef387c7ceb
version: 1.0.0
dataset_uuid: deb426d2-5ea7-42ae-ae97-c99694c2ddff
