slice_name: SI - Share Class Filter for Today's Deal
description: null
certified_by: null
certification_details: null
viz_type: filter_box
params:
  adhoc_filters:
  - clause: WHERE
    comparator: 'Yes'
    expressionType: SIMPLE
    filterOptionName: filter_4wxzqd2g6_cjl0eefxmpi
    isExtra: false
    isNew: false
    operator: ==
    operatorId: EQUALS
    sqlExpression: null
    subject: CURRENT DAY FLAG
  datasource: 57__table
  date_filter: false
  extra_form_data: {}
  filter_configs:
  - asc: true
    clearable: true
    column: share_class_name
    key: -cezVyh7M
    label: SHARE CLASS
    multiple: true
    searchAllOptions: false
  granularity_sqla: bookvp_date
  instant_filtering: true
  slice_id: 239
  time_grain_sqla: P1D
  time_range: No filter
  url_params: {}
  viz_type: filter_box
query_context: null
cache_timeout: null
uuid: 7bb88364-fdab-034f-ec1e-7dd428270fc2
version: 1.0.0
dataset_uuid: 425aaa80-69f3-bb87-0d4c-9b280593557b
