slice_name: SI - Complaints Resolved by Category Group
viz_type: pie
params:
  adhoc_filters: []
  color_scheme: supersetColors
  datasource: 49__table
  date_format: smart_date
  donut: true
  extra_form_data: {}
  granularity_sqla: resolved_date
  groupby:
  - incident_category_group
  innerRadius: 50
  label_line: true
  label_type: key
  labels_outside: true
  legendOrientation: top
  legendType: scroll
  metric: TOTAL_RESOLVED
  number_format: SMART_NUMBER
  outerRadius: 65
  row_limit: 100
  show_labels: true
  show_labels_threshold: 5
  show_legend: true
  slice_id: 182
  sort_by_metric: true
  time_range: Last 12 months
  url_params: {}
  viz_type: pie
cache_timeout: null
uuid: 4625014b-6657-8313-2b58-d7bb08801cc3
version: 1.0.0
dataset_uuid: e5094f0c-5391-2731-3de4-8bfb236135c9
