slice_name: SI - Total Deals
viz_type: big_number_total
params:
  adhoc_filters: []
  datasource: 95__table
  extra_form_data: {}
  granularity_sqla: deal_date
  header_font_size: 0.4
  metric:
    aggregate: COUNT_DISTINCT
    column:
      certification_details: null
      certified_by: null
      column_name: deal_id
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 3190
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: VARCHAR(20)
      type_generic: 1
      verbose_name: null
      warning_markdown: null
    expressionType: SIMPLE
    hasCustomLabel: false
    isNew: false
    label: COUNT_DISTINCT(deal_id)
    optionName: metric_kq85aio478b_yuyphkjk3x
    sqlExpression: null
  slice_id: 501
  subheader_font_size: 0.15
  time_format: '%d-%m-%Y %H:%M:%S'
  time_range: 'DATEADD(DATETIME("today"), -2, month) : today'
  url_params: {}
  viz_type: big_number_total
  y_axis_format: ',d'
cache_timeout: null
uuid: cb8980c7-d1f0-4238-8b46-5e06dd720180
version: 1.0.0
dataset_uuid: 1f183292-9794-4769-b7a7-a08acfeb402a
