slice_name: SI - Dealing Volume
description: null
certified_by: null
certification_details: null
viz_type: dist_bar
params:
  adhoc_filters:
  - clause: WHERE
    comparator: 'Yes'
    expressionType: SIMPLE
    filterOptionName: filter_cz7zkaqs73r_nzem91vp86n
    isExtra: false
    isNew: false
    operator: '!='
    operatorId: NOT_EQUALS
    sqlExpression: null
    subject: CURRENT DAY FLAG
  bar_stacked: true
  bottom_margin: auto
  color_scheme: supersetColors
  columns:
  - Deal Origin for STP
  datasource: 57__table
  extra_form_data: {}
  granularity_sqla: bookvp_date
  groupby:
  - Time of Trade VP
  metrics:
  - aggregate: COUNT_DISTINCT
    column:
      certification_details: null
      certified_by: null
      column_name: deal_id
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 966
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: VARCHAR(20)
      type_generic: 1
      verbose_name: Deal ID
      warning_markdown: null
    expressionType: SIMPLE
    hasCustomLabel: false
    isNew: false
    label: COUNT_DISTINCT(Deal ID)
    optionName: metric_lgmkyj9yjm_q9eo0kq7hu
    sqlExpression: null
  order_bars: true
  order_desc: true
  reduce_x_ticks: false
  row_limit: 10000
  show_legend: true
  slice_id: 485
  time_range: '2022-11-04T00:00:00 : 2022-11-05T00:00:00'
  url_params: {}
  viz_type: dist_bar
  x_ticks_layout: flat
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
query_context: null
cache_timeout: null
uuid: 7bab9295-0531-4e0e-a967-91b81107ca7c
version: 1.0.0
dataset_uuid: 425aaa80-69f3-bb87-0d4c-9b280593557b
