slice_name: SI - Complaints Resolved Category Filter
viz_type: filter_box
params:
  adhoc_filters:
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_xbizmgp9z08_6s1n7z0rav2
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: resolved_date IS NOT NULL
    subject: null
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_gr7bvhkf_rukxadw7tri
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: complaint_status NOT IN ('Void')
    subject: null
  datasource: 49__table
  date_filter: false
  extra_form_data: {}
  filter_configs:
  - asc: true
    clearable: true
    column: incident_category_group
    key: DjBPdUe4J
    label: COMPLAINT CATEGORY GROUP
    multiple: true
    searchAllOptions: false
  granularity_sqla: received_date
  instant_filtering: true
  slice_id: 509
  time_grain_sqla: P1D
  time_range: No filter
  url_params: {}
  viz_type: filter_box
cache_timeout: null
uuid: d55df0f9-2029-4711-b351-26470076ffe8
version: 1.0.0
dataset_uuid: e5094f0c-5391-2731-3de4-8bfb236135c9
