slice_name: SI - Voided Breach Details
description: Version 1.1 (23-08-2021) CDIG001 Confidential
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters:
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_mrqk63xotqj_jzimd8edyjm
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: void_date >= date_trunc('Week',(current_date - INTERVAL '3 weeks'))::date
    subject: null
  all_columns:
  - days_since_voided_txt
  - breach_ref
  - client_ref
  - client_name
  - void_date
  - control_refs
  color_pn: true
  datasource: 48__table
  extra_form_data: {}
  granularity_sqla: void_date
  groupby: []
  include_search: true
  metrics:
  - count
  order_by_cols:
  - '["days_since_voided_txt", false]'
  order_desc: true
  page_length: 20
  percent_metrics: []
  query_mode: raw
  row_limit: 10000
  server_page_length: 10
  show_cell_bars: false
  slice_id: 176
  table_timestamp_format: smart_date
  time_grain_sqla: P1D
  time_range: No filter
  url_params: {}
  viz_type: table
query_context: null
cache_timeout: null
uuid: a3066b55-1f9e-63ae-b705-a419c6e1ff78
version: 1.0.0
dataset_uuid: f8317c8b-7468-9302-8dd4-bb1298e9d50c
