slice_name: SI - Today's Negative Movements
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters:
  - clause: WHERE
    comparator: '0'
    expressionType: SIMPLE
    filterOptionName: filter_ckrz92r0m99_br7k4ly48wf
    isExtra: false
    isNew: false
    operator: <
    operatorId: LESS_THAN
    sqlExpression: null
    subject: fund_movement_value
  all_columns:
  - fund_code
  - share_class_name
  - isin_code
  - PRICE STATUS TXT
  - last_price_amount
  - NAV
  - Today's Movement
  - Today's Movement %
  color_pn: true
  column_config:
    NAV:
      d3NumberFormat: ',.2f'
      d3SmallNumberFormat: ',.2f'
    Today's Movement:
      d3NumberFormat: ',.2f'
      d3SmallNumberFormat: ',.2f'
    Today's Movement %:
      d3NumberFormat: ',.2%'
      d3SmallNumberFormat: ',.2%'
      showCellBars: false
    last_price_amount:
      d3NumberFormat: ',.4f'
      d3SmallNumberFormat: ',.4f'
  conditional_formatting: []
  datasource: 58__table
  extra_form_data: {}
  groupby: []
  metrics:
  - count
  order_by_cols:
  - '["Today''s Movement", true]'
  order_desc: true
  page_length: 20
  percent_metrics: []
  query_mode: raw
  row_limit: 10000
  server_page_length: 10
  show_cell_bars: false
  slice_id: 342
  table_timestamp_format: smart_date
  time_grain_sqla: P1D
  time_range: No filter
  url_params: {}
  viz_type: table
query_context: null
cache_timeout: null
uuid: 07c956ff-bcc6-4620-be9f-167a06c1d9be
version: 1.0.0
dataset_uuid: c28fef52-923b-a734-0b83-4cec471c48cc
