slice_name: SI - Total of Cancelled Deals
viz_type: pie
params:
  adhoc_filters: []
  color_scheme: supersetColors
  datasource: 95__table
  date_format: '%d/%m/%Y'
  donut: true
  extra_form_data: {}
  granularity_sqla: deal_date
  groupby:
  - Deal Cancelled
  innerRadius: 50
  label_line: true
  label_type: key_percent
  labels_outside: true
  legendOrientation: top
  legendType: scroll
  metric:
    aggregate: COUNT_DISTINCT
    column:
      certification_details: null
      certified_by: null
      column_name: deal_id
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 3190
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: VARCHAR(20)
      type_generic: 1
      verbose_name: Deal ID
      warning_markdown: null
    expressionType: SIMPLE
    hasCustomLabel: false
    isNew: false
    label: COUNT_DISTINCT(Deal ID)
    optionName: metric_3ishiihr2j7_u28csqrvene
    sqlExpression: null
  number_format: ',d'
  outerRadius: 65
  row_limit: 100
  show_labels: true
  show_labels_threshold: ''
  show_legend: true
  slice_id: 504
  sort_by_metric: true
  time_range: 'DATEADD(DATETIME("today"), -2, month) : today'
  url_params: {}
  viz_type: pie
cache_timeout: null
uuid: 02faf013-1133-4131-8ac3-846c864097c2
version: 1.0.0
dataset_uuid: 1f183292-9794-4769-b7a7-a08acfeb402a
