slice_name: SI - Negative Net Movements
viz_type: table
params:
  adhoc_filters:
  - clause: WHERE
    comparator: '0'
    expressionType: SIMPLE
    filterOptionName: filter_8mjwepmybat_w3dd0h01j6
    isExtra: false
    isNew: false
    operator: <
    operatorId: LESS_THAN
    sqlExpression: null
    subject: fund_movement_value
  all_columns:
  - fund_name
  - Today's Movement
  - Today's Movement %
  color_pn: false
  column_config:
    Today's Movement:
      d3NumberFormat: ',.2f'
      d3SmallNumberFormat: ',.2f'
      showCellBars: false
    Today's Movement %:
      d3NumberFormat: ',.2%'
      d3SmallNumberFormat: ',.2%'
      showCellBars: false
  conditional_formatting: []
  datasource: 58__table
  extra_form_data: {}
  groupby:
  - fund_name
  include_search: true
  metrics:
  - aggregate: SUM
    column:
      certification_details: null
      certified_by: null
      column_name: Today's Movement
      description: null
      expression: fund_movement_value
      filterable: true
      groupby: true
      id: 2106
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: NUMERIC
      type_generic: 0
      verbose_name: Today's Movement
      warning_markdown: null
    expressionType: SIMPLE
    hasCustomLabel: true
    isNew: false
    label: Today's Movement
    optionName: metric_5hxo2mphijc_e4bh7o88a6d
    sqlExpression: null
  - aggregate: SUM
    column:
      certification_details: null
      certified_by: null
      column_name: Today's Movement %
      description: null
      expression: fund_movement_percent
      filterable: true
      groupby: true
      id: 2109
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: NUMERIC
      type_generic: 0
      verbose_name: Today's Movement %
      warning_markdown: null
    expressionType: SIMPLE
    hasCustomLabel: true
    isNew: false
    label: Today's Movement %
    optionName: metric_4nkhsn5m3me_dt02sfpwhac
    sqlExpression: null
  order_by_cols:
  - '["Today''s Movement", true]'
  order_desc: false
  page_length: 20
  percent_metrics: []
  query_mode: aggregate
  row_limit: 10000
  server_page_length: 10
  show_cell_bars: false
  slice_id: 238
  table_timestamp_format: smart_date
  time_grain_sqla: P1D
  time_range: No filter
  timeseries_limit_metric:
    aggregate: SUM
    column:
      certification_details: null
      certified_by: null
      column_name: Today's Movement
      description: null
      expression: fund_movement_value
      filterable: true
      groupby: true
      id: 2106
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: NUMERIC
      type_generic: 0
      verbose_name: Today's Movement
      warning_markdown: null
    expressionType: SIMPLE
    hasCustomLabel: false
    isNew: false
    label: SUM(Today's Movement)
    optionName: metric_0g67p9rcqnei_gher7pc8dlo
    sqlExpression: null
  url_params: {}
  viz_type: table
cache_timeout: null
uuid: 32bdff72-60b9-ddb5-37d9-09770db54a25
version: 1.0.0
dataset_uuid: c28fef52-923b-a734-0b83-4cec471c48cc
