slice_name: SI - Complaints Resolved Filters
description: null
certified_by: null
certification_details: null
viz_type: filter_box
params:
  adhoc_filters:
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_eb0hxhwkhu6_4dl558quph4
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: complaint_status NOT IN ('Void')
    subject: null
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_bdo1yinmx2t_lfjhz0agjc
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: resolved_date IS NOT NULL
    subject: null
  datasource: 49__table
  date_filter: true
  extra_form_data: {}
  filter_configs: []
  granularity_sqla: resolved_date
  instant_filtering: true
  slice_id: 187
  time_grain_sqla: P1D
  time_range: No filter
  url_params: {}
  viz_type: filter_box
query_context: null
cache_timeout: null
uuid: 015e3b37-0655-c3b3-391a-98389bcf0605
version: 1.0.0
dataset_uuid: e5094f0c-5391-2731-3de4-8bfb236135c9
