slice_name: SI - Complaints by Category
description: Version 1.0 (23-08-2021) CDIG001 Confidential
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters:
  - clause: WHERE
    comparator:
    - Void
    expressionType: SIMPLE
    filterOptionName: filter_bppkrx6n39v_avi4h3e5x6i
    isExtra: false
    isNew: false
    operator: NOT IN
    sqlExpression: null
    subject: complaint_status
  all_columns: []
  color_pn: true
  column_config:
    COUNT:
      d3NumberFormat: ',d'
      d3SmallNumberFormat: ',d'
      showCellBars: false
  conditional_formatting: []
  datasource: 49__table
  extra_form_data: {}
  granularity_sqla: received_date
  groupby:
  - incident_category_group
  include_search: false
  metrics:
  - COUNT
  order_by_cols: []
  order_desc: true
  percent_metrics: []
  query_mode: aggregate
  row_limit: 10000
  server_page_length: 10
  show_cell_bars: false
  slice_id: 180
  table_timestamp_format: smart_date
  time_grain_sqla: null
  time_range: 'DATEADD(DATETIME("now"), -4, week) : now'
  url_params: {}
  viz_type: table
query_context: null
cache_timeout: null
uuid: 1977c09e-ab37-4cbe-b72d-c0f476dfc43c
version: 1.0.0
dataset_uuid: e5094f0c-5391-2731-3de4-8bfb236135c9
