slice_name: SI - Non-END Manual Dealing Work Items
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters:
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_4k8l5o5ofhm_1i903lum6ki
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: manual_deal_flag='Yes'
    subject: null
  - clause: WHERE
    comparator: END
    expressionType: SIMPLE
    filterOptionName: filter_yucevurl0nb_5o1uz69hi97
    isExtra: false
    isNew: false
    operator: '!='
    sqlExpression: null
    subject: queuecd
  all_columns:
  - awd_crdattim
  - unitcd
  - wrktype
  - processing_stage
  - suspend_flag
  - age_bus_days_band
  - uh_id
  - agent_id
  color_pn: true
  datasource: 50__table
  extra_form_data: {}
  granularity_sqla: last_update_dattim
  groupby: []
  include_search: true
  metrics:
  - count
  order_by_cols:
  - '["awd_crdattim", true]'
  order_desc: true
  page_length: 10
  percent_metrics: []
  query_mode: raw
  row_limit: 10000
  server_page_length: 10
  show_cell_bars: false
  slice_id: 148
  table_timestamp_format: smart_date
  time_grain_sqla: P1D
  time_range: No filter
  url_params: {}
  viz_type: table
query_context: null
cache_timeout: null
uuid: 17594048-23fe-cc3c-3518-9492da5df03c
version: 1.0.0
dataset_uuid: 40f6d689-5a50-6435-4ddd-353a5940ae24
