slice_name: SI - Manual Deals
viz_type: big_number_total
params:
  adhoc_filters:
  - clause: WHERE
    comparator: END
    expressionType: SIMPLE
    filterOptionName: filter_wu56acqiry_iujuzvnlpk
    isExtra: false
    isNew: false
    operator: '!='
    sqlExpression: null
    subject: queuecd
  - clause: WHERE
    comparator: 'Yes'
    expressionType: SIMPLE
    filterOptionName: filter_1qzhnj2jsud_b6s476c96jm
    isExtra: false
    isNew: false
    operator: ==
    sqlExpression: null
    subject: manual_deal_flag
  datasource: 46__table
  extra_form_data: {}
  granularity_sqla: last_update_dattim
  header_font_size: 0.4
  metric: count
  slice_id: 206
  subheader_font_size: 0.15
  time_format: smart_date
  time_grain_sqla: P1D
  time_range: No filter
  viz_type: big_number_total
  y_axis_format: SMART_NUMBER
cache_timeout: null
uuid: 9325b461-9b8f-4e83-a33a-e77d3dbc5fc1
version: 1.0.0
dataset_uuid: 40f6d689-5a50-6435-4ddd-353a5940ae24
