slice_name: SI - Non-END Referred Work Items
viz_type: table
params:
  adhoc_filters:
  - clause: WHERE
    comparator: Management Company Refer
    expressionType: SIMPLE
    filterOptionName: filter_npopeom5lbp_atwx65is2hi
    isExtra: false
    isNew: false
    operator: ==
    sqlExpression: null
    subject: owner_team
  - clause: WHERE
    comparator: END
    expressionType: SIMPLE
    filterOptionName: filter_bxdofe7weu_y983mn92shm
    isExtra: false
    isNew: false
    operator: '!='
    sqlExpression: null
    subject: queuecd
  all_columns:
  - awd_crdattim
  - unitcd
  - wrktype
  - processing_stage
  - suspend_flag
  - age_bus_days_band
  - uh_id
  - agent_id
  color_pn: true
  datasource: 50__table
  extra_form_data: {}
  granularity_sqla: last_update_dattim
  groupby: []
  include_search: true
  metrics:
  - count
  order_by_cols:
  - '["awd_crdattim", true]'
  order_desc: true
  page_length: 10
  percent_metrics: []
  query_mode: raw
  row_limit: 10000
  server_page_length: 10
  show_cell_bars: false
  slice_id: 149
  table_timestamp_format: smart_date
  time_grain_sqla: P1D
  time_range: No filter
  url_params: {}
  viz_type: table
cache_timeout: null
uuid: 328888da-a908-5df6-e1e2-e47751043547
version: 1.0.0
dataset_uuid: 40f6d689-5a50-6435-4ddd-353a5940ae24
