slice_name: SI - Breaches Overview
description: Version 1.0 (23-08-2021) CDIG001 Confidential
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters:
  - clause: WHERE
    comparator:
    - Other
    expressionType: SIMPLE
    filterOptionName: filter_j3dcz8suvc_wp3s2tdaida
    isExtra: false
    isNew: false
    operator: not in
    sqlExpression: null
    subject: merge_date
  all_columns: []
  color_pn: true
  datasource: 48__table
  granularity_sqla: date_identified
  groupby:
  - merge_date
  metrics:
  - TOTAL_NOTIFIED
  - TOTAL_CLOSED
  - TOTAL_VOIDED
  order_by_cols: []
  order_desc: true
  percent_metrics: []
  query_mode: aggregate
  row_limit: 10000
  show_cell_bars: false
  slice_id: 173
  table_timestamp_format: smart_date
  time_grain_sqla: P1D
  time_range: No filter
  timeseries_limit_metric: []
  url_params: {}
  viz_type: table
query_context: null
cache_timeout: null
uuid: 7c329654-d302-8c17-ae3b-38e7c2e8e82c
version: 1.0.0
dataset_uuid: f8317c8b-7468-9302-8dd4-bb1298e9d50c
