slice_name: SI - Complaints Outstanding Filter
description: Version 1.0 (23-08-2021) CDIG001 Confidential
certified_by: null
certification_details: null
viz_type: filter_box
params:
  adhoc_filters:
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_cakx2lbcodu_jpujmzwrlw
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: resolute_letter_date IS NULL
    subject: null
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_a9k0m9h97o8_daqombugyuc
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: UPPER(complaint_status) NOT IN ('VOID')
    subject: null
  datasource: 49__table
  date_filter: false
  extra_form_data: {}
  filter_configs:
  - asc: true
    clearable: true
    column: incident_category_group
    key: 8Uxe7Kwpy
    label: COMPLAINT CATEGORY GROUP
    multiple: true
    searchAllOptions: false
  granularity_sqla: received_date
  instant_filtering: true
  slice_id: 188
  time_grain_sqla: P1D
  time_range: No filter
  url_params: {}
  viz_type: filter_box
query_context: null
cache_timeout: null
uuid: 75b1e92f-dff8-302c-6f3c-ea469e271d20
version: 1.0.0
dataset_uuid: e5094f0c-5391-2731-3de4-8bfb236135c9
