slice_name: SI - Total Significant Breaches
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  adhoc_filters:
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_owsh7r04qmj_ekz5yvpzas
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: original_closed_date >= date_trunc('Week',(current_date - INTERVAL
      '3weeks'))::date
    subject: null
  datasource: 48__table
  extra_form_data: {}
  granularity_sqla: notified_mc_date
  header_font_size: 0.4
  metric: Total
  slice_id: 511
  subheader_font_size: 0.15
  time_format: '%d-%m-%Y %H:%M:%S'
  time_range: No filter
  url_params: {}
  viz_type: big_number_total
  y_axis_format: ',d'
query_context: '{"datasource": {"id": 48, "type": "table"}, "force": false, "queries":
  [{"time_range": "No filter", "granularity": "notified_mc_date", "filters": [], "extras":
  {"having": "", "having_druid": [], "where": "(original_closed_date >= date_trunc(''Week'',(current_date
  - INTERVAL ''3weeks''))::date)"}, "applied_time_extras": {}, "columns": [], "metrics":
  ["Total"], "annotation_layers": [], "timeseries_limit": 0, "order_desc": true, "url_params":
  {}, "custom_params": {}, "custom_form_data": {}}], "result_format": "json", "result_type":
  "full"}'
cache_timeout: null
uuid: d12d183e-7c08-412d-b0a2-bfb6b84b5ef7
version: 1.0.0
dataset_uuid: f8317c8b-7468-9302-8dd4-bb1298e9d50c
