slice_name: SI - Today's Notifiable Deals by Origin
description: null
certified_by: null
certification_details: null
viz_type: dist_bar
params:
  adhoc_filters:
  - clause: WHERE
    comparator: 'Yes'
    expressionType: SIMPLE
    filterOptionName: filter_eyyyvkoy51m_bt45da1izw5
    isExtra: false
    isNew: false
    operator: ==
    operatorId: EQUALS
    sqlExpression: null
    subject: CURRENT DAY FLAG
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_ecjydw2cn9_txe0cpgjp4s
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: RTRIM(transaction_type_desc) <> 'Stock Transfer In'
    subject: null
  - clause: WHERE
    comparator: Y
    expressionType: SIMPLE
    filterOptionName: filter_6asqesktmk_r62fwhl07fn
    isExtra: false
    isNew: false
    operator: '!='
    sqlExpression: null
    subject: cancelled_flag
  bar_stacked: true
  bottom_margin: auto
  color_scheme: supersetColors
  columns:
  - fund_name
  datasource: 51__table
  extra_form_data: {}
  groupby:
  - deal_origin
  metrics:
  - count
  order_desc: true
  row_limit: 10000
  show_controls: false
  show_legend: false
  slice_id: 160
  time_range: No filter
  url_params: {}
  viz_type: dist_bar
  x_ticks_layout: "45\xB0"
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
query_context: null
cache_timeout: null
uuid: d65201dc-de5f-6e05-9ab4-2d97ed706124
version: 1.0.0
dataset_uuid: 47f9e1f7-837a-05ee-d094-bf9eb1a8be98
