slice_name: SI - Notifiable Deals
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters:
  - clause: WHERE
    comparator: 'Yes'
    expressionType: SIMPLE
    filterOptionName: filter_pk27ux9tye_pdmxxfxuhnc
    isExtra: false
    isNew: false
    operator: ==
    sqlExpression: null
    subject: CURRENT DAY FLAG
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_eodk2v810n_jap6t55orx
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: RTRIM(transaction_type_desc) <> 'Stock Transfer In'
    subject: null
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_rrnra9knaxj_k5tcpt4t4iq
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: cancelled_flag <> 'Y'
    subject: null
  all_columns:
  - event_id
  - transaction_type_desc
  - Est. Actual Cash
  color_pn: false
  datasource: 51__table
  extra_form_data: {}
  groupby: []
  metrics:
  - count
  order_by_cols:
  - '["time_of_deal", false]'
  order_desc: true
  page_length: 0
  percent_metrics: []
  query_mode: raw
  row_limit: 10000
  server_page_length: 10
  show_cell_bars: false
  slice_id: 161
  table_timestamp_format: smart_date
  time_grain_sqla: P1D
  time_range: No filter
  url_params: {}
  viz_type: table
query_context: null
cache_timeout: null
uuid: 5cca67a3-df38-49db-8c4a-9dfc1b959a50
version: 1.0.0
dataset_uuid: 47f9e1f7-837a-05ee-d094-bf9eb1a8be98
