slice_name: SI - Active Work Processing Stage Filter
viz_type: filter_box
params:
  adhoc_filters:
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_ht4g6n9ix39_e4w6ppc3gfw
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: processing_stage <> 'End'
    subject: null
  datasource: 50__table
  date_filter: false
  extra_form_data: {}
  filter_configs:
  - asc: true
    clearable: true
    column: processing_stage
    key: KPMmb8I_1
    label: Processing Stage
    metric: Processing stage filter
    multiple: true
    searchAllOptions: false
  granularity_sqla: last_update_dattim
  instant_filtering: true
  slice_id: 317
  time_grain_sqla: P1D
  time_range: No filter
  url_params: {}
  viz_type: filter_box
cache_timeout: null
uuid: 6f609570-f852-4b5f-b0e8-aebcb7cce4a8
version: 1.0.0
dataset_uuid: 40f6d689-5a50-6435-4ddd-353a5940ae24
