slice_name: SI - Non-END Work Items
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters:
  - clause: WHERE
    comparator: END
    expressionType: SIMPLE
    filterOptionName: filter_ek5jengpaqo_fnzeadx21ut
    isExtra: false
    isNew: false
    operator: '!='
    sqlExpression: null
    subject: queuecd
  all_columns:
  - awd_crdattim
  - unitcd
  - wrktype
  - processing_stage
  - suspend_flag
  - age_bus_days_band
  - uh_id
  - agent_id
  color_pn: true
  conditional_formatting: []
  datasource: 50__table
  extra_form_data: {}
  granularity_sqla: last_update_dattim
  groupby: []
  include_search: true
  metrics:
  - count
  order_by_cols:
  - '["awd_crdattim", true]'
  order_desc: true
  percent_metrics: []
  query_mode: raw
  row_limit: 10000
  server_page_length: 20
  server_pagination: true
  show_cell_bars: false
  slice_id: 150
  table_timestamp_format: smart_date
  time_grain_sqla: P1D
  time_range: No filter
  url_params: {}
  viz_type: table
query_context: null
cache_timeout: null
uuid: 08f4fea2-d9a1-26e0-2b60-3c3ddb549c81
version: 1.0.0
dataset_uuid: 40f6d689-5a50-6435-4ddd-353a5940ae24
