slice_name: SUP - Manco Mapping
description: A pivot table displaying the Manco  reference mapping for each system
  and relating them to a 'manco group' for each manco
certified_by: null
certification_details: null
viz_type: pivot_table
params:
  adhoc_filters: []
  columns:
  - instance_type
  - currency
  combine_metric: true
  datasource: 47__table
  date_format: smart_date
  groupby:
  - mco_name
  metrics:
  - aggregate: MAX
    column:
      column_name: ein
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 667
      is_dttm: false
      python_date_format: null
      type: INTEGER
      verbose_name: null
    expressionType: SIMPLE
    hasCustomLabel: true
    isNew: false
    label: EIN
    optionName: metric_i62qt7lmxkp_6vpp1ywifsd
    sqlExpression: null
  - aggregate: MAX
    column:
      column_name: mc_ext_ref
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 671
      is_dttm: false
      optionName: _col_mc_ext_ref
      python_date_format: null
      type: VARCHAR(25)
      verbose_name: null
    expressionType: SIMPLE
    hasCustomLabel: true
    isNew: false
    label: Ext Ref
    optionName: metric_867m5t2oxha_sq2ztsbiquq
    sqlExpression: null
  - aggregate: MAX
    column:
      column_name: ext_env_id
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 670
      is_dttm: false
      optionName: _col_ext_env_id
      python_date_format: null
      type: VARCHAR(25)
      verbose_name: null
    expressionType: SIMPLE
    hasCustomLabel: true
    isNew: false
    label: Ext Env ID
    optionName: metric_jszhcsyaz3_j0mu9uayum
    sqlExpression: null
  number_format: ~g
  pandas_aggfunc: sum
  pivot_margins: false
  row_limit: null
  slice_id: 146
  time_grain_sqla: P1D
  time_range: No filter
  transpose_pivot: false
  url_params: {}
  viz_type: pivot_table
query_context: null
cache_timeout: null
uuid: 5f471f87-bc49-5db0-e809-973dc80e4677
version: 1.0.0
dataset_uuid: 9a8d10d9-ddab-ce94-c003-5f6f275d928f
