slice_name: Top 10 Boy Name Share
viz_type: area
params:
  adhoc_filters:
  - clause: WHERE
    comparator: boy
    expressionType: SIMPLE
    operator: ==
    subject: gender
  compare_lag: '10'
  compare_suffix: o10Y
  comparison_type: values
  granularity_sqla: ds
  groupby:
  - name
  limit: 10
  markup_type: markdown
  metrics:
  - aggregate: SUM
    column:
      column_name: num
      type: BIGINT
    expressionType: SIMPLE
    label: Births
    optionName: metric_11
  row_limit: 50000
  since: 100 years ago
  stacked_style: expand
  time_grain_sqla: P1D
  time_range: No filter
  until: now
  viz_type: area
  x_axis_forma: smart_date
cache_timeout: null
uuid: 58212cc6-6475-445d-93f6-23044a0e6750
version: 1.0.0
dataset_uuid: 5f4d9b3a-846b-4ae1-adc6-4bcb1cf5bcc9
