slice_name: Top 10 California Names Timeseries
description: null
certified_by: null
certification_details: null
viz_type: line
params:
  compare_lag: '10'
  compare_suffix: o10Y
  granularity_sqla: ds
  groupby:
  - name
  limit: '10'
  markup_type: markdown
  metrics:
  - aggregate: SUM
    column:
      column_name: num_california
      expression: CASE WHEN state = 'CA' THEN num ELSE 0 END
    expressionType: SIMPLE
    label: SUM(num_california)
  row_limit: 50000
  time_range: '100 years ago : now'
  timeseries_limit_metric:
    aggregate: SUM
    column:
      column_name: num_california
      expression: CASE WHEN state = 'CA' THEN num ELSE 0 END
    expressionType: SIMPLE
    label: SUM(num_california)
  viz_type: line
query_context: null
cache_timeout: null
uuid: 03df3ab3-8665-496a-80ff-1842f715f53e
version: 1.0.0
dataset_uuid: 29e854db-68af-463f-b0a1-7acd63bfccdd
