slice_name: Top 10 California Names Timeseries
viz_type: line
params:
  compare_lag: '10'
  compare_suffix: o10Y
  granularity_sqla: ds
  groupby:
  - name
  limit: '10'
  markup_type: markdown
  metrics:
  - aggregate: SUM
    column:
      column_name: num_california
      expression: CASE WHEN state = 'CA' THEN num ELSE 0 END
    expressionType: SIMPLE
    label: SUM(num_california)
  row_limit: 50000
  since: 100 years ago
  time_range: No filter
  timeseries_limit_metric:
    aggregate: SUM
    column:
      column_name: num_california
      expression: CASE WHEN state = 'CA' THEN num ELSE 0 END
    expressionType: SIMPLE
    label: SUM(num_california)
  until: now
  viz_type: line
cache_timeout: null
uuid: 118d6c23-7c81-4fb0-9f12-9565d43d5f7d
version: 1.0.0
dataset_uuid: 2f14b67b-aebd-47af-970c-83258a649d99
