slice_name: Trends
viz_type: line
params:
  compare_lag: '10'
  compare_suffix: o10Y
  granularity_sqla: ds
  groupby:
  - name
  limit: '25'
  markup_type: markdown
  metrics:
  - aggregate: SUM
    column:
      column_name: num
      type: BIGINT
    expressionType: SIMPLE
    label: Births
    optionName: metric_11
  rich_tooltip: true
  row_limit: 50000
  show_legend: true
  since: 100 years ago
  time_range: No filter
  until: now
  viz_type: line
cache_timeout: null
uuid: 792ea968-bb5a-4e2b-aa9d-3ba65099583d
version: 1.0.0
dataset_uuid: 77361041-c96a-4c59-87fe-8730f9a6ddb1
