slice_name: Use For Test Pipeline2
description: null
certified_by: null
certification_details: null
viz_type: pie
params:
  adhoc_filters:
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_tpmczlauh7_pgoxzswpag
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: UPPER(queuecd) <> 'END'
    subject: null
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_8xcxpu98cfj_2622syavu1l
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: UPPER(wrktype) = 'FXTRADE'
    subject: null
  color_scheme: supersetColors
  datasource: 96__table
  date_format: smart_date
  donut: true
  extra_form_data: {}
  granularity_sqla: last_update_dattim
  groupby:
  - processing_stage
  innerRadius: 50
  label_line: true
  label_type: key
  labels_outside: true
  legendOrientation: top
  legendType: scroll
  metric: count
  number_format: ',d'
  outerRadius: 65
  row_limit: 100
  show_labels: true
  show_labels_threshold: 5
  show_legend: false
  sort_by_metric: true
  time_range: No filter
  viz_type: pie
query_context: '{"datasource":{"id":96,"type":"table"},"force":false,"queries":[{"time_range":"No
  filter","granularity":"last_update_dattim","filters":[],"extras":{"having":"","having_druid":[],"where":"(UPPER(queuecd)
  <> ''END'') AND (UPPER(wrktype) = ''FXTRADE'')"},"applied_time_extras":{},"columns":["processing_stage"],"metrics":["count"],"orderby":[["count",false]],"annotation_layers":[],"row_limit":100,"timeseries_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"96__table","viz_type":"pie","slice_id":2000000001,"granularity_sqla":"last_update_dattim","time_range":"No
  filter","groupby":["processing_stage"],"metric":"count","adhoc_filters":[{"clause":"WHERE","comparator":null,"expressionType":"SQL","filterOptionName":"filter_tpmczlauh7_pgoxzswpag","isExtra":false,"isNew":false,"operator":null,"sqlExpression":"UPPER(queuecd)
  <> ''END''","subject":null},{"clause":"WHERE","comparator":null,"expressionType":"SQL","filterOptionName":"filter_8xcxpu98cfj_2622syavu1l","isExtra":false,"isNew":false,"operator":null,"sqlExpression":"UPPER(wrktype)
  = ''FXTRADE''","subject":null}],"row_limit":100,"sort_by_metric":true,"color_scheme":"supersetColors","show_labels_threshold":5,"show_legend":false,"legendType":"scroll","legendOrientation":"top","label_type":"key","number_format":",d","date_format":"smart_date","show_labels":true,"labels_outside":true,"label_line":true,"outerRadius":65,"donut":true,"innerRadius":50,"extra_form_data":{},"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: dffc381f-40a4-4b0f-a4c8-6f6eb7d34e72
version: 1.0.0
dataset_uuid: 2c52393b-92f3-4a51-9ff7-3d0349ae0245
