slice_name: World's Population
viz_type: big_number
params:
  compare_lag: '10'
  compare_suffix: over 10Y
  country_fieldtype: cca3
  entity: country_code
  granularity_sqla: year
  groupby: []
  limit: '25'
  markup_type: markdown
  metric: sum__SP_POP_TOTL
  row_limit: 50000
  show_bubbles: true
  since: '2000'
  time_range: '2014-01-01 : 2014-01-02'
  until: '2014-01-02'
  viz_type: big_number
cache_timeout: null
uuid: ee17b80b-00c3-42e9-bfbf-cc231b1b039d
version: 1.0.0
dataset_uuid: 8ed131ea-0048-485f-88de-6105e7422210
