slice_name: World's Pop Growth
viz_type: area
params:
  compare_lag: '10'
  compare_suffix: o10Y
  country_fieldtype: cca3
  entity: country_code
  granularity_sqla: year
  groupby:
  - region
  limit: '25'
  markup_type: markdown
  metrics:
  - sum__SP_POP_TOTL
  row_limit: 50000
  show_bubbles: true
  since: '1960-01-01'
  time_range: '2014-01-01 : 2014-01-02'
  until: now
  viz_type: area
cache_timeout: null
uuid: 916b85ce-9b73-42f1-ab9c-92abc8444948
version: 1.0.0
dataset_uuid: 8ed131ea-0048-485f-88de-6105e7422210
