slice_name: World's Population
viz_type: big_number
params:
  compare_lag: '10'
  compare_suffix: over 10Y
  country_fieldtype: cca3
  entity: country_code
  granularity_sqla: year
  groupby: []
  limit: '25'
  markup_type: markdown
  metric: sum__SP_POP_TOTL
  row_limit: 50000
  show_bubbles: true
  since: '2000'
  time_range: '2014-01-01 : 2014-01-02'
  until: '2014-01-02'
  viz_type: big_number
cache_timeout: null
uuid: fb4fb4d6-087d-4bee-9b92-d79cbe466e26
version: 1.0.0
dataset_uuid: 51ee505c-9969-4526-8e72-46d002aa3889
