slice_name: FMR - UHS - Total by Currency
viz_type: table
params:
  adhoc_filters:
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_drfg2jsigrh_f6i14omam2l
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: units_unsett_est+units_unsett_act+units_sett<>0
    subject: null
  all_columns: []
  color_pn: true
  datasource: 54__table
  granularity_sqla: latest_valuation_date
  groupby:
  - ccy_id
  metrics:
  - aggregate: null
    column: null
    expressionType: SQL
    hasCustomLabel: true
    isNew: false
    label: Total Investment Value
    optionName: metric_d99ywk82qo7_slipokkew
    sqlExpression: SUM((units_unsett_est+units_unsett_act+units_sett)*latest_price_amount)
  order_by_cols: []
  order_desc: true
  percent_metrics: []
  query_mode: aggregate
  row_limit: null
  show_cell_bars: false
  slice_id: 210
  table_timestamp_format: smart_date
  time_grain_sqla: P1D
  time_range: No filter
  url_params: {}
  viz_type: table
cache_timeout: null
uuid: 29b77a64-24f0-c18e-2f08-62c7c3f63f8d
version: 1.0.0
dataset_uuid: 294bb475-bd97-fe6c-dec6-ec4cd42fc6fa
