slice_name: FMR - UHS - Summary Filters
viz_type: filter_box
params:
  adhoc_filters: []
  datasource: 54__table
  date_filter: false
  filter_configs:
  - asc: true
    clearable: false
    column: bua_name
    defaultValue: Select an Investor
    key: qxgTohQFs
    label: Investor Name
    multiple: false
    searchAllOptions: true
  granularity_sqla: latest_valuation_date
  instant_filtering: true
  slice_id: 206
  time_grain_sqla: P1D
  time_range: No filter
  url_params: {}
  viz_type: filter_box
cache_timeout: null
uuid: 935917a3-4a01-952b-1238-d86199be4d09
version: 1.0.0
dataset_uuid: 294bb475-bd97-fe6c-dec6-ec4cd42fc6fa
