slice_name: SI0 - Outstanding breaches by age
viz_type: dist_bar
params:
  adhoc_filters: []
  bar_stacked: false
  bottom_margin: auto
  color_scheme: supersetColors
  columns: null
  datasource: 20__table
  granularity_sqla: identified_date
  groupby:
  - Demo_age
  label_colors:
    Closed: '#0097A9'
    Data Protection: '#A4D65E'
    Not SS&C Error: '#BD374A'
    Not Significant: '#454E7C'
    Other: '#0097A9'
    Primary CASS: '#6F5091'
    Procedure: '#0097A9'
    Quality Checking: '#6F5091'
    Significant: '#5AC189'
    System: '#D9C89E'
    Total Number of Breaches: '#1FA8C9'
    Total items: '#00677F'
    Total outstanding breaches: '#0097A9'
    Voided: '#00677F'
  metrics:
  - aggregate: COUNT
    column:
      column_name: breach_ref
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 324
      is_dttm: false
      optionName: _col_breach_ref
      python_date_format: null
      type: VARCHAR(13)
      verbose_name: null
    expressionType: SIMPLE
    hasCustomLabel: true
    isNew: false
    label: Total outstanding breaches
    optionName: metric_8axfc83okb4_cslsc9mjjcb
    sqlExpression: null
  order_bars: true
  reduce_x_ticks: false
  row_limit: 10000
  show_bar_value: false
  show_controls: false
  show_legend: false
  slice_id: 70
  time_range: No filter
  url_params: {}
  viz_type: dist_bar
  x_axis_label: Age
  x_ticks_layout: flat
  y_axis_format: SMART_NUMBER
  y_axis_label: Number of Breaches
cache_timeout: null
uuid: a2481d40-96fb-4280-b26e-42b1632d88ea
version: 1.0.0
dataset_uuid: e86bd959-0878-588a-29d9-31157bd1370b
