slice_name: SI0 - Outstanding Complaints by Age
viz_type: dist_bar
params:
  adhoc_filters: []
  bottom_margin: auto
  color_scheme: supersetColors
  columns: []
  datasource: 16__table
  granularity_sqla: received_date
  groupby:
  - comp_age
  label_colors: {}
  metrics:
  - count
  order_bars: true
  queryFields:
    columns: groupby
    groupby: groupby
    metrics: metrics
  row_limit: 10000
  show_bar_value: true
  show_legend: false
  time_range: No filter
  url_params: {}
  viz_type: dist_bar
  x_axis_label: Age in Working Days
  x_ticks_layout: auto
  y_axis_format: SMART_NUMBER
  y_axis_label: Number of Complaints
cache_timeout: null
uuid: cd69cdca-4a12-5b8b-913e-c6b0c2e84fd3
version: 1.0.0
dataset_uuid: 53d7ac4c-c765-3cf2-0f5a-bca3a8b3b625
