slice_name: SI4 - Total Cancelled Deals
viz_type: big_number_total
params:
  adhoc_filters:
  - clause: WHERE
    comparator: Y
    expressionType: SIMPLE
    filterOptionName: filter_u2ag9qak4h_0bxdra5notk9
    isExtra: false
    isNew: false
    operator: ==
    operatorId: EQUALS
    sqlExpression: null
    subject: cancelled
  datasource: 93__table
  extra_form_data: {}
  granularity_sqla: eff_date
  header_font_size: 0.4
  metric:
    aggregate: COUNT_DISTINCT
    column:
      certification_details: null
      certified_by: null
      column_name: deal_id
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 3124
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: VARCHAR(20)
      type_generic: 1
      verbose_name: Transaction ID
      warning_markdown: null
    expressionType: SIMPLE
    hasCustomLabel: false
    isNew: false
    label: COUNT_DISTINCT(Transaction ID)
    optionName: metric_7p0qq9lb3c5_5dnlcrsblsq
    sqlExpression: null
  slice_id: 419
  subheader: ''
  subheader_font_size: 0.15
  time_format: '%d-%m-%Y %H:%M:%S'
  time_range: 'DATEADD(DATETIME("now"), -2, month) : now'
  url_params: {}
  viz_type: big_number_total
  y_axis_format: SMART_NUMBER
cache_timeout: null
uuid: 19dfe368-e88b-429a-b3f7-a28133369551
version: 1.0.0
dataset_uuid: 74fa6896-5e25-4630-b057-9f43589743fa
