slice_name: SI5- Outstanding Breach Details
viz_type: table
params:
  adhoc_filters:
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_gblhb9o69c7_if17ff76w0l
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: upper(breach_status) NOT IN ('VOID', 'CLOSED')
    subject: null
  all_columns:
  - days_since_identified_txt
  - breach_ref
  - unitholder_id
  - client_id
  - date_identified
  - part_outstanding
  - control_refs
  color_pn: false
  column_config:
    date_identified:
      d3TimeFormat: '%Y-%m-%d'
  conditional_formatting: []
  datasource: 97__table
  extra_form_data: {}
  granularity_sqla: update_datetime
  groupby: []
  include_search: true
  order_by_cols:
  - '["date_identified", true]'
  order_desc: true
  page_length: 20
  percent_metrics: []
  query_mode: raw
  row_limit: 10000
  server_page_length: 10
  show_cell_bars: false
  slice_id: 517
  table_timestamp_format: smart_date
  time_grain_sqla: P1D
  time_range: No filter
  url_params: {}
  viz_type: table
cache_timeout: null
uuid: e8d83fd1-b435-4673-84a2-a8bb834c02f9
version: 1.0.0
dataset_uuid: 9f0a237b-3856-4149-9f7b-70e2e9a25367
