slice_name: SI0 - Complaints Resolved Filters
viz_type: filter_box
params:
  adhoc_filters: []
  datasource: 14__table
  date_filter: true
  filter_configs:
  - asc: true
    clearable: true
    column: category_group
    key: cskuy0r2F
    label: Complaint Category Group
    multiple: true
    searchAllOptions: false
  granularity_sqla: resolved_date
  instant_filtering: true
  queryFields: {}
  time_range: No filter
  url_params: {}
  viz_type: filter_box
cache_timeout: null
uuid: 1538952a-d7d0-5da5-8e80-c2b0b7cba50e
version: 1.0.0
dataset_uuid: c2a9fe9e-ff47-13b1-3e32-484896e4481c
