slice_name: SI - Assets Under Management
viz_type: big_number_total
params:
  adhoc_filters: []
  datasource: 58__table
  header_font_size: 0.4
  metric: Last Fund Value
  slice_id: 244
  subheader_font_size: 0.15
  time_range: Last week
  url_params: {}
  viz_type: big_number_total
  y_axis_format: SMART_NUMBER
cache_timeout: null
uuid: a8022b90-6a33-43f3-9c25-cff9c361931d
version: 1.0.0
dataset_uuid: c28fef52-923b-a734-0b83-4cec471c48cc
